// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

enum abstract DownlevelFlag(Int) from Int to Int {
	var ComputeShaders = 0;
	var FragmentWritableStorage = 1;
	var IndirectExecution = 2;
	var BaseVertex = 3;
	var ReadOnlyDepthStencil = 4;
	var NonPowerOfTwoMipmappedTextures = 5;
	var CubeArrayTextures = 6;
	var ComparisonSamplers = 7;
	var IndependentBlend = 8;
	var VertexStorage = 9;
	var AnisotropicFiltering = 10;
	var FragmentStorage = 11;
	var MultisampledShading = 12;
	var DepthTextureAndBufferCopies = 13;
	var WebgpuTextureFormatSupport = 14;
	var BufferBindingsNot16ByteAligned = 15;
	var UnrestrictedIndexBuffer = 16;
	var FullDrawIndexUint32 = 17;
	var DepthBiasClamp = 18;
	var ViewFormats = 19;
	var UnrestrictedExternalTextureCopies = 20;
	var SurfaceViewFormats = 21;
	var NonblockingQueryResolve = 22;
	var ShaderF16InF32 = 23;
	var Msl21 = 24;
	var TextureCompression = 25;
}
