// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuAccelerationStructureBuild(hl.Abstract<"xgpu_GpuAccelerationStructureBuild">) {
	public inline function new() this = GpuAccelerationStructureBuildNative.create();
	public inline function addBlases(value:GpuBlasBuildEntry):Void GpuAccelerationStructureBuildNative.addBlases(this, value);
	public inline function addTlases(value:GpuTlas):Void GpuAccelerationStructureBuildNative.addTlases(this, value);
}

private extern class GpuAccelerationStructureBuildNative {
	@:hlNative("xgpu", "gpu_acceleration_structure_build_new")
	public static function create():hl.Abstract<"xgpu_GpuAccelerationStructureBuild">;
	@:hlNative("xgpu", "gpu_acceleration_structure_build_add_blases")
	public static function addBlases(self:hl.Abstract<"xgpu_GpuAccelerationStructureBuild">, value:GpuBlasBuildEntry):Void;
	@:hlNative("xgpu", "gpu_acceleration_structure_build_add_tlases")
	public static function addTlases(self:hl.Abstract<"xgpu_GpuAccelerationStructureBuild">, value:GpuTlas):Void;
}
