// Generated by xgpu-bindgen. Do not edit by hand.
package gpu;

abstract GpuAdapter(Int) from Int to Int {
	public inline function valid():Bool return GpuAdapterNative.valid(this);
	public inline function name():String { var value = GpuAdapterNative.name(this); return value == null ? null : @:privateAccess String.fromUCS2(value); };
	public inline function backend():Backend return GpuAdapterNative.backend(this);
	public inline function limit(which:Limit):haxe.Int64 return GpuAdapterNative.limit(this, which);
	public inline function supports(feature:Feature):Bool return GpuAdapterNative.supports(this, feature);
	public inline function destroy():Void GpuAdapterNative.destroy(this);
	public inline function requestDevice():ash.Future<GpuDevice> return GpuAdapterNative.requestDevice(this);
	public inline function requestDeviceWith(descriptor:GpuDeviceDescriptor):ash.Future<GpuDevice> return GpuAdapterNative.requestDeviceWith(this, descriptor);
	public inline function driver():String { var value = GpuAdapterNative.driver(this); return value == null ? null : @:privateAccess String.fromUCS2(value); };
	public inline function driverInfo():String { var value = GpuAdapterNative.driverInfo(this); return value == null ? null : @:privateAccess String.fromUCS2(value); };
	public inline function supportsNative(feature:NativeFeature):Bool return GpuAdapterNative.supportsNative(this, feature);
	public inline function nativeLimit(which:NativeLimit):haxe.Int64 return GpuAdapterNative.nativeLimit(this, which);
	public inline function textureFormatUsages(format:TextureFormat):Int return GpuAdapterNative.textureFormatUsages(this, format);
	public inline function textureFormatFeatures(format:TextureFormat):Int return GpuAdapterNative.textureFormatFeatures(this, format);
	public inline function vendorId():haxe.Int64 return GpuAdapterNative.vendorId(this);
	public inline function deviceId():haxe.Int64 return GpuAdapterNative.deviceId(this);
	public inline function deviceType():DeviceType return GpuAdapterNative.deviceType(this);
	public inline function pciBusId():String { var value = GpuAdapterNative.pciBusId(this); return value == null ? null : @:privateAccess String.fromUCS2(value); };
	public inline function subgroupMinSize():Int return GpuAdapterNative.subgroupMinSize(this);
	public inline function subgroupMaxSize():Int return GpuAdapterNative.subgroupMaxSize(this);
	public inline function pipelineCacheKey():String { var value = GpuAdapterNative.pipelineCacheKey(this); return value == null ? null : @:privateAccess String.fromUCS2(value); };
}

private extern class GpuAdapterNative {
	@:hlNative("xgpu", "gpu_adapter_valid")
	public static function valid(self:Int):Bool;
	@:hlNative("xgpu", "gpu_adapter_name")
	public static function name(self:Int):hl.Bytes;
	@:hlNative("xgpu", "gpu_adapter_backend")
	public static function backend(self:Int):Backend;
	@:hlNative("xgpu", "gpu_adapter_limit")
	public static function limit(self:Int, which:Limit):haxe.Int64;
	@:hlNative("xgpu", "gpu_adapter_supports")
	public static function supports(self:Int, feature:Feature):Bool;
	@:hlNative("xgpu", "gpu_adapter_destroy")
	public static function destroy(self:Int):Void;
	@:hlNative("xgpu", "gpu_adapter_request_device")
	public static function requestDevice(self:Int):ash.Future<GpuDevice>;
	@:hlNative("xgpu", "gpu_adapter_request_device_with")
	public static function requestDeviceWith(self:Int, descriptor:GpuDeviceDescriptor):ash.Future<GpuDevice>;
	@:hlNative("xgpu", "gpu_adapter_driver")
	public static function driver(self:Int):hl.Bytes;
	@:hlNative("xgpu", "gpu_adapter_driver_info")
	public static function driverInfo(self:Int):hl.Bytes;
	@:hlNative("xgpu", "gpu_adapter_supports_native")
	public static function supportsNative(self:Int, feature:NativeFeature):Bool;
	@:hlNative("xgpu", "gpu_adapter_native_limit")
	public static function nativeLimit(self:Int, which:NativeLimit):haxe.Int64;
	@:hlNative("xgpu", "gpu_adapter_texture_format_usages")
	public static function textureFormatUsages(self:Int, format:TextureFormat):Int;
	@:hlNative("xgpu", "gpu_adapter_texture_format_features")
	public static function textureFormatFeatures(self:Int, format:TextureFormat):Int;
	@:hlNative("xgpu", "gpu_adapter_vendor_id")
	public static function vendorId(self:Int):haxe.Int64;
	@:hlNative("xgpu", "gpu_adapter_device_id")
	public static function deviceId(self:Int):haxe.Int64;
	@:hlNative("xgpu", "gpu_adapter_device_type")
	public static function deviceType(self:Int):DeviceType;
	@:hlNative("xgpu", "gpu_adapter_pci_bus_id")
	public static function pciBusId(self:Int):hl.Bytes;
	@:hlNative("xgpu", "gpu_adapter_subgroup_min_size")
	public static function subgroupMinSize(self:Int):Int;
	@:hlNative("xgpu", "gpu_adapter_subgroup_max_size")
	public static function subgroupMaxSize(self:Int):Int;
	@:hlNative("xgpu", "gpu_adapter_pipeline_cache_key")
	public static function pipelineCacheKey(self:Int):hl.Bytes;
}
