// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuAccelerationStructureBindingLayout(hl.Abstract<"xidl_GpuAccelerationStructureBindingLayout">) {
	public inline function new() this = GpuAccelerationStructureBindingLayoutNative.create();
	public inline function vertexReturn(value:Bool):Void GpuAccelerationStructureBindingLayoutNative.vertexReturn(this, value);
}

private extern class GpuAccelerationStructureBindingLayoutNative {
	@:hlNative("xidl", "gpu_acceleration_structure_binding_layout_new")
	public static function create():hl.Abstract<"xidl_GpuAccelerationStructureBindingLayout">;
	@:hlNative("xidl", "gpu_acceleration_structure_binding_layout_vertex_return")
	public static function vertexReturn(self:hl.Abstract<"xidl_GpuAccelerationStructureBindingLayout">, value:Bool):Void;
}
