// Generated by xgpu-bindgen. Do not edit by hand.
package gpu;

abstract GpuBlendState(hl.Abstract<"xgpu_GpuBlendState">) {
	public inline function new(color:GpuBlendComponent, alpha:GpuBlendComponent) this = GpuBlendStateNative.create(color, alpha);
}

private extern class GpuBlendStateNative {
	@:hlNative("xgpu", "gpu_blend_state_new")
	public static function create(color:GpuBlendComponent, alpha:GpuBlendComponent):hl.Abstract<"xgpu_GpuBlendState">;
}
