// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuBufferBindingLayout(hl.Abstract<"xidl_GpuBufferBindingLayout">) {
	public inline function new() this = GpuBufferBindingLayoutNative.create();
	public inline function type(value:BufferBindingType):Void GpuBufferBindingLayoutNative.type(this, value);
	public inline function hasDynamicOffset(value:Bool):Void GpuBufferBindingLayoutNative.hasDynamicOffset(this, value);
	public inline function minBindingSize(value:haxe.Int64):Void GpuBufferBindingLayoutNative.minBindingSize(this, value);
}

private extern class GpuBufferBindingLayoutNative {
	@:hlNative("xidl", "gpu_buffer_binding_layout_new")
	public static function create():hl.Abstract<"xidl_GpuBufferBindingLayout">;
	@:hlNative("xidl", "gpu_buffer_binding_layout_type")
	public static function type(self:hl.Abstract<"xidl_GpuBufferBindingLayout">, value:BufferBindingType):Void;
	@:hlNative("xidl", "gpu_buffer_binding_layout_has_dynamic_offset")
	public static function hasDynamicOffset(self:hl.Abstract<"xidl_GpuBufferBindingLayout">, value:Bool):Void;
	@:hlNative("xidl", "gpu_buffer_binding_layout_min_binding_size")
	public static function minBindingSize(self:hl.Abstract<"xidl_GpuBufferBindingLayout">, value:haxe.Int64):Void;
}
