// Generated by xgpu-bindgen. Do not edit by hand.
package gpu;

abstract GpuBlasDescriptor(hl.Abstract<"xgpu_GpuBlasDescriptor">) {
	public inline function new() this = GpuBlasDescriptorNative.create();
	public inline function label(value:String):Void GpuBlasDescriptorNative.label(this, value);
	public inline function flags(value:Int):Void GpuBlasDescriptorNative.flags(this, value);
	public inline function updateMode(value:AccelerationStructureUpdateMode):Void GpuBlasDescriptorNative.updateMode(this, value);
	public inline function addTriangles(value:GpuBlasTriangleGeometrySize):Void GpuBlasDescriptorNative.addTriangles(this, value);
	public inline function addAabbs(value:GpuBlasAabbGeometrySize):Void GpuBlasDescriptorNative.addAabbs(this, value);
}

private extern class GpuBlasDescriptorNative {
	@:hlNative("xgpu", "gpu_blas_descriptor_new")
	public static function create():hl.Abstract<"xgpu_GpuBlasDescriptor">;
	@:hlNative("xgpu", "gpu_blas_descriptor_label")
	public static function label(self:hl.Abstract<"xgpu_GpuBlasDescriptor">, value:String):Void;
	@:hlNative("xgpu", "gpu_blas_descriptor_flags")
	public static function flags(self:hl.Abstract<"xgpu_GpuBlasDescriptor">, value:Int):Void;
	@:hlNative("xgpu", "gpu_blas_descriptor_update_mode")
	public static function updateMode(self:hl.Abstract<"xgpu_GpuBlasDescriptor">, value:AccelerationStructureUpdateMode):Void;
	@:hlNative("xgpu", "gpu_blas_descriptor_add_triangles")
	public static function addTriangles(self:hl.Abstract<"xgpu_GpuBlasDescriptor">, value:GpuBlasTriangleGeometrySize):Void;
	@:hlNative("xgpu", "gpu_blas_descriptor_add_aabbs")
	public static function addAabbs(self:hl.Abstract<"xgpu_GpuBlasDescriptor">, value:GpuBlasAabbGeometrySize):Void;
}
