// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuBufferArray(hl.Abstract<"xidl_GpuBufferArray">) {
	public inline function new() this = GpuBufferArrayNative.create();
	public inline function addBuffers(value:GpuBufferBinding):Void GpuBufferArrayNative.addBuffers(this, value);
}

private extern class GpuBufferArrayNative {
	@:hlNative("xidl", "gpu_buffer_array_new")
	public static function create():hl.Abstract<"xidl_GpuBufferArray">;
	@:hlNative("xidl", "gpu_buffer_array_add_buffers")
	public static function addBuffers(self:hl.Abstract<"xidl_GpuBufferArray">, value:GpuBufferBinding):Void;
}
