// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuBufferBinding(hl.Abstract<"xgpu_GpuBufferBinding">) {
	public inline function new(buffer:GpuBuffer) this = GpuBufferBindingNative.create(buffer);
	public inline function offset(value:haxe.Int64):Void GpuBufferBindingNative.offset(this, value);
	public inline function size(value:haxe.Int64):Void GpuBufferBindingNative.size(this, value);
}

private extern class GpuBufferBindingNative {
	@:hlNative("xgpu", "gpu_buffer_binding_new")
	public static function create(buffer:GpuBuffer):hl.Abstract<"xgpu_GpuBufferBinding">;
	@:hlNative("xgpu", "gpu_buffer_binding_offset")
	public static function offset(self:hl.Abstract<"xgpu_GpuBufferBinding">, value:haxe.Int64):Void;
	@:hlNative("xgpu", "gpu_buffer_binding_size")
	public static function size(self:hl.Abstract<"xgpu_GpuBufferBinding">, value:haxe.Int64):Void;
}
