// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuBlas(Int) from Int to Int {
	public inline function valid():Bool return GpuBlasNative.valid(this);
	public inline function destroy():Void GpuBlasNative.destroy(this);
	public inline function prepareCompaction():ash.Future<Void> return GpuBlasNative.prepareCompaction(this);
	public inline function readyForCompaction():Bool return GpuBlasNative.readyForCompaction(this);
}

private extern class GpuBlasNative {
	@:hlNative("xidl", "gpu_blas_valid")
	public static function valid(self:Int):Bool;
	@:hlNative("xidl", "gpu_blas_destroy")
	public static function destroy(self:Int):Void;
	@:hlNative("xidl", "gpu_blas_prepare_compaction")
	public static function prepareCompaction(self:Int):ash.Future<Void>;
	@:hlNative("xidl", "gpu_blas_ready_for_compaction")
	public static function readyForCompaction(self:Int):Bool;
}
