// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuBlasAabbGeometrySize(hl.Abstract<"xidl_GpuBlasAabbGeometrySize">) {
	public inline function new(primitiveCount:Int) this = GpuBlasAabbGeometrySizeNative.create(primitiveCount);
	public inline function flags(value:Int):Void GpuBlasAabbGeometrySizeNative.flags(this, value);
}

private extern class GpuBlasAabbGeometrySizeNative {
	@:hlNative("xidl", "gpu_blas_aabb_geometry_size_new")
	public static function create(primitiveCount:Int):hl.Abstract<"xidl_GpuBlasAabbGeometrySize">;
	@:hlNative("xidl", "gpu_blas_aabb_geometry_size_flags")
	public static function flags(self:hl.Abstract<"xidl_GpuBlasAabbGeometrySize">, value:Int):Void;
}
