// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuBufferDescriptor(hl.Abstract<"xgpu_GpuBufferDescriptor">) {
	public inline function new(size:haxe.Int64, usage:Int) this = GpuBufferDescriptorNative.create(size, usage);
	public inline function label(value:String):Void GpuBufferDescriptorNative.label(this, value);
	public inline function mappedAtCreation(value:Bool):Void GpuBufferDescriptorNative.mappedAtCreation(this, value);
}

private extern class GpuBufferDescriptorNative {
	@:hlNative("xgpu", "gpu_buffer_descriptor_new")
	public static function create(size:haxe.Int64, usage:Int):hl.Abstract<"xgpu_GpuBufferDescriptor">;
	@:hlNative("xgpu", "gpu_buffer_descriptor_label")
	public static function label(self:hl.Abstract<"xgpu_GpuBufferDescriptor">, value:String):Void;
	@:hlNative("xgpu", "gpu_buffer_descriptor_mapped_at_creation")
	public static function mappedAtCreation(self:hl.Abstract<"xgpu_GpuBufferDescriptor">, value:Bool):Void;
}
