// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuBindGroupEntry(hl.Abstract<"xgpu_GpuBindGroupEntry">) {
	public inline function new(binding:Int) this = GpuBindGroupEntryNative.create(binding);
	public inline function resourceSampler(value:GpuSampler):Void GpuBindGroupEntryNative.resourceSampler(this, value);
	public inline function resourceTexture(value:GpuTexture):Void GpuBindGroupEntryNative.resourceTexture(this, value);
	public inline function resourceTextureView(value:GpuTextureView):Void GpuBindGroupEntryNative.resourceTextureView(this, value);
	public inline function resourceBuffer(value:GpuBuffer):Void GpuBindGroupEntryNative.resourceBuffer(this, value);
	public inline function resourceBufferBinding(value:GpuBufferBinding):Void GpuBindGroupEntryNative.resourceBufferBinding(this, value);
	public inline function resourceExternalTexture(value:GpuExternalTexture):Void GpuBindGroupEntryNative.resourceExternalTexture(this, value);
	public inline function resourceBufferArray(value:GpuBufferArray):Void GpuBindGroupEntryNative.resourceBufferArray(this, value);
	public inline function resourceSamplerArray(value:GpuSamplerArray):Void GpuBindGroupEntryNative.resourceSamplerArray(this, value);
	public inline function resourceTextureViewArray(value:GpuTextureViewArray):Void GpuBindGroupEntryNative.resourceTextureViewArray(this, value);
	public inline function resourceAccelerationStructure(value:GpuTlas):Void GpuBindGroupEntryNative.resourceAccelerationStructure(this, value);
	public inline function resourceAccelerationStructureArray(value:GpuTlasArray):Void GpuBindGroupEntryNative.resourceAccelerationStructureArray(this, value);
}

private extern class GpuBindGroupEntryNative {
	@:hlNative("xgpu", "gpu_bind_group_entry_new")
	public static function create(binding:Int):hl.Abstract<"xgpu_GpuBindGroupEntry">;
	@:hlNative("xgpu", "gpu_bind_group_entry_resource_sampler")
	public static function resourceSampler(self:hl.Abstract<"xgpu_GpuBindGroupEntry">, value:GpuSampler):Void;
	@:hlNative("xgpu", "gpu_bind_group_entry_resource_texture")
	public static function resourceTexture(self:hl.Abstract<"xgpu_GpuBindGroupEntry">, value:GpuTexture):Void;
	@:hlNative("xgpu", "gpu_bind_group_entry_resource_texture_view")
	public static function resourceTextureView(self:hl.Abstract<"xgpu_GpuBindGroupEntry">, value:GpuTextureView):Void;
	@:hlNative("xgpu", "gpu_bind_group_entry_resource_buffer")
	public static function resourceBuffer(self:hl.Abstract<"xgpu_GpuBindGroupEntry">, value:GpuBuffer):Void;
	@:hlNative("xgpu", "gpu_bind_group_entry_resource_buffer_binding")
	public static function resourceBufferBinding(self:hl.Abstract<"xgpu_GpuBindGroupEntry">, value:GpuBufferBinding):Void;
	@:hlNative("xgpu", "gpu_bind_group_entry_resource_external_texture")
	public static function resourceExternalTexture(self:hl.Abstract<"xgpu_GpuBindGroupEntry">, value:GpuExternalTexture):Void;
	@:hlNative("xgpu", "gpu_bind_group_entry_resource_buffer_array")
	public static function resourceBufferArray(self:hl.Abstract<"xgpu_GpuBindGroupEntry">, value:GpuBufferArray):Void;
	@:hlNative("xgpu", "gpu_bind_group_entry_resource_sampler_array")
	public static function resourceSamplerArray(self:hl.Abstract<"xgpu_GpuBindGroupEntry">, value:GpuSamplerArray):Void;
	@:hlNative("xgpu", "gpu_bind_group_entry_resource_texture_view_array")
	public static function resourceTextureViewArray(self:hl.Abstract<"xgpu_GpuBindGroupEntry">, value:GpuTextureViewArray):Void;
	@:hlNative("xgpu", "gpu_bind_group_entry_resource_acceleration_structure")
	public static function resourceAccelerationStructure(self:hl.Abstract<"xgpu_GpuBindGroupEntry">, value:GpuTlas):Void;
	@:hlNative("xgpu", "gpu_bind_group_entry_resource_acceleration_structure_array")
	public static function resourceAccelerationStructureArray(self:hl.Abstract<"xgpu_GpuBindGroupEntry">, value:GpuTlasArray):Void;
}
