// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuBlendComponent(hl.Abstract<"xidl_GpuBlendComponent">) {
	public inline function new() this = GpuBlendComponentNative.create();
	public inline function operation(value:BlendOperation):Void GpuBlendComponentNative.operation(this, value);
	public inline function srcFactor(value:BlendFactor):Void GpuBlendComponentNative.srcFactor(this, value);
	public inline function dstFactor(value:BlendFactor):Void GpuBlendComponentNative.dstFactor(this, value);
}

private extern class GpuBlendComponentNative {
	@:hlNative("xidl", "gpu_blend_component_new")
	public static function create():hl.Abstract<"xidl_GpuBlendComponent">;
	@:hlNative("xidl", "gpu_blend_component_operation")
	public static function operation(self:hl.Abstract<"xidl_GpuBlendComponent">, value:BlendOperation):Void;
	@:hlNative("xidl", "gpu_blend_component_src_factor")
	public static function srcFactor(self:hl.Abstract<"xidl_GpuBlendComponent">, value:BlendFactor):Void;
	@:hlNative("xidl", "gpu_blend_component_dst_factor")
	public static function dstFactor(self:hl.Abstract<"xidl_GpuBlendComponent">, value:BlendFactor):Void;
}
