// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuBlasTriangleGeometry(hl.Abstract<"xidl_GpuBlasTriangleGeometry">) {
	public inline function new(size:GpuBlasTriangleGeometrySize, vertexBuffer:GpuBuffer, vertexStride:haxe.Int64) this = GpuBlasTriangleGeometryNative.create(size, vertexBuffer, vertexStride);
	public inline function firstVertex(value:Int):Void GpuBlasTriangleGeometryNative.firstVertex(this, value);
	public inline function indexBuffer(value:GpuBuffer):Void GpuBlasTriangleGeometryNative.indexBuffer(this, value);
	public inline function firstIndex(value:Int):Void GpuBlasTriangleGeometryNative.firstIndex(this, value);
	public inline function transformBuffer(value:GpuBuffer):Void GpuBlasTriangleGeometryNative.transformBuffer(this, value);
	public inline function transformBufferOffset(value:haxe.Int64):Void GpuBlasTriangleGeometryNative.transformBufferOffset(this, value);
}

private extern class GpuBlasTriangleGeometryNative {
	@:hlNative("xidl", "gpu_blas_triangle_geometry_new")
	public static function create(size:GpuBlasTriangleGeometrySize, vertexBuffer:GpuBuffer, vertexStride:haxe.Int64):hl.Abstract<"xidl_GpuBlasTriangleGeometry">;
	@:hlNative("xidl", "gpu_blas_triangle_geometry_first_vertex")
	public static function firstVertex(self:hl.Abstract<"xidl_GpuBlasTriangleGeometry">, value:Int):Void;
	@:hlNative("xidl", "gpu_blas_triangle_geometry_index_buffer")
	public static function indexBuffer(self:hl.Abstract<"xidl_GpuBlasTriangleGeometry">, value:GpuBuffer):Void;
	@:hlNative("xidl", "gpu_blas_triangle_geometry_first_index")
	public static function firstIndex(self:hl.Abstract<"xidl_GpuBlasTriangleGeometry">, value:Int):Void;
	@:hlNative("xidl", "gpu_blas_triangle_geometry_transform_buffer")
	public static function transformBuffer(self:hl.Abstract<"xidl_GpuBlasTriangleGeometry">, value:GpuBuffer):Void;
	@:hlNative("xidl", "gpu_blas_triangle_geometry_transform_buffer_offset")
	public static function transformBufferOffset(self:hl.Abstract<"xidl_GpuBlasTriangleGeometry">, value:haxe.Int64):Void;
}
