// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuBindGroup(Int) from Int to Int {
	public inline function valid():Bool return GpuBindGroupNative.valid(this);
	public inline function destroy():Void GpuBindGroupNative.destroy(this);
}

private extern class GpuBindGroupNative {
	@:hlNative("xgpu", "gpu_bind_group_valid")
	public static function valid(self:Int):Bool;
	@:hlNative("xgpu", "gpu_bind_group_destroy")
	public static function destroy(self:Int):Void;
}
