// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuBindGroupLayoutEntry(hl.Abstract<"xgpu_GpuBindGroupLayoutEntry">) {
	public inline function new(binding:Int, visibility:Int) this = GpuBindGroupLayoutEntryNative.create(binding, visibility);
	public inline function buffer(value:GpuBufferBindingLayout):Void GpuBindGroupLayoutEntryNative.buffer(this, value);
	public inline function sampler(value:GpuSamplerBindingLayout):Void GpuBindGroupLayoutEntryNative.sampler(this, value);
	public inline function texture(value:GpuTextureBindingLayout):Void GpuBindGroupLayoutEntryNative.texture(this, value);
	public inline function storageTexture(value:GpuStorageTextureBindingLayout):Void GpuBindGroupLayoutEntryNative.storageTexture(this, value);
	public inline function externalTexture(value:GpuExternalTextureBindingLayout):Void GpuBindGroupLayoutEntryNative.externalTexture(this, value);
	public inline function count(value:Int):Void GpuBindGroupLayoutEntryNative.count(this, value);
	public inline function accelerationStructure(value:GpuAccelerationStructureBindingLayout):Void GpuBindGroupLayoutEntryNative.accelerationStructure(this, value);
}

private extern class GpuBindGroupLayoutEntryNative {
	@:hlNative("xgpu", "gpu_bind_group_layout_entry_new")
	public static function create(binding:Int, visibility:Int):hl.Abstract<"xgpu_GpuBindGroupLayoutEntry">;
	@:hlNative("xgpu", "gpu_bind_group_layout_entry_buffer")
	public static function buffer(self:hl.Abstract<"xgpu_GpuBindGroupLayoutEntry">, value:GpuBufferBindingLayout):Void;
	@:hlNative("xgpu", "gpu_bind_group_layout_entry_sampler")
	public static function sampler(self:hl.Abstract<"xgpu_GpuBindGroupLayoutEntry">, value:GpuSamplerBindingLayout):Void;
	@:hlNative("xgpu", "gpu_bind_group_layout_entry_texture")
	public static function texture(self:hl.Abstract<"xgpu_GpuBindGroupLayoutEntry">, value:GpuTextureBindingLayout):Void;
	@:hlNative("xgpu", "gpu_bind_group_layout_entry_storage_texture")
	public static function storageTexture(self:hl.Abstract<"xgpu_GpuBindGroupLayoutEntry">, value:GpuStorageTextureBindingLayout):Void;
	@:hlNative("xgpu", "gpu_bind_group_layout_entry_external_texture")
	public static function externalTexture(self:hl.Abstract<"xgpu_GpuBindGroupLayoutEntry">, value:GpuExternalTextureBindingLayout):Void;
	@:hlNative("xgpu", "gpu_bind_group_layout_entry_count")
	public static function count(self:hl.Abstract<"xgpu_GpuBindGroupLayoutEntry">, value:Int):Void;
	@:hlNative("xgpu", "gpu_bind_group_layout_entry_acceleration_structure")
	public static function accelerationStructure(self:hl.Abstract<"xgpu_GpuBindGroupLayoutEntry">, value:GpuAccelerationStructureBindingLayout):Void;
}
