// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuBindGroupLayout(Int) from Int to Int {
	public inline function valid():Bool return GpuBindGroupLayoutNative.valid(this);
	public inline function destroy():Void GpuBindGroupLayoutNative.destroy(this);
}

private extern class GpuBindGroupLayoutNative {
	@:hlNative("xgpu", "gpu_bind_group_layout_valid")
	public static function valid(self:Int):Bool;
	@:hlNative("xgpu", "gpu_bind_group_layout_destroy")
	public static function destroy(self:Int):Void;
}
