// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuBindings(Int) from Int to Int {
	public inline function new() this = GpuBindingsNative.create();
	public inline function valid():Bool return GpuBindingsNative.valid(this);
	public inline function buffer(buffer:GpuBuffer):Void GpuBindingsNative.buffer(this, buffer);
	public inline function texture(view:GpuTextureView):Void GpuBindingsNative.texture(this, view);
	public inline function sampler(sampler:GpuSampler):Void GpuBindingsNative.sampler(this, sampler);
	public inline function destroy():Void GpuBindingsNative.destroy(this);
}

private extern class GpuBindingsNative {
	@:hlNative("xgpu", "gpu_bindings_new")
	public static function create():GpuBindings;
	@:hlNative("xgpu", "gpu_bindings_valid")
	public static function valid(self:Int):Bool;
	@:hlNative("xgpu", "gpu_bindings_buffer")
	public static function buffer(self:Int, buffer:GpuBuffer):Void;
	@:hlNative("xgpu", "gpu_bindings_texture")
	public static function texture(self:Int, view:GpuTextureView):Void;
	@:hlNative("xgpu", "gpu_bindings_sampler")
	public static function sampler(self:Int, sampler:GpuSampler):Void;
	@:hlNative("xgpu", "gpu_bindings_destroy")
	public static function destroy(self:Int):Void;
}
