// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuBindGroupDescriptor(hl.Abstract<"xidl_GpuBindGroupDescriptor">) {
	public inline function new(layout:GpuBindGroupLayout) this = GpuBindGroupDescriptorNative.create(layout);
	public inline function label(value:String):Void GpuBindGroupDescriptorNative.label(this, value);
	public inline function addEntries(value:GpuBindGroupEntry):Void GpuBindGroupDescriptorNative.addEntries(this, value);
}

private extern class GpuBindGroupDescriptorNative {
	@:hlNative("xidl", "gpu_bind_group_descriptor_new")
	public static function create(layout:GpuBindGroupLayout):hl.Abstract<"xidl_GpuBindGroupDescriptor">;
	@:hlNative("xidl", "gpu_bind_group_descriptor_label")
	public static function label(self:hl.Abstract<"xidl_GpuBindGroupDescriptor">, value:String):Void;
	@:hlNative("xidl", "gpu_bind_group_descriptor_add_entries")
	public static function addEntries(self:hl.Abstract<"xidl_GpuBindGroupDescriptor">, value:GpuBindGroupEntry):Void;
}
