// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuBuffer(Int) from Int to Int {
	public inline function valid():Bool return GpuBufferNative.valid(this);
	public inline function copyOut(offset:haxe.Int64, out:haxe.io.Bytes, len:Int):Bool return GpuBufferNative.copyOut(this, offset, out, len);
	public inline function copyIn(offset:haxe.Int64, data:haxe.io.Bytes, len:Int):Bool return GpuBufferNative.copyIn(this, offset, data, len);
	public inline function size():haxe.Int64 return GpuBufferNative.size(this);
	public inline function usage():Int return GpuBufferNative.usage(this);
	public inline function unmap():Void GpuBufferNative.unmap(this);
	public inline function destroy():Void GpuBufferNative.destroy(this);
}

private extern class GpuBufferNative {
	@:hlNative("xidl", "gpu_buffer_valid")
	public static function valid(self:Int):Bool;
	@:hlNative("xidl", "gpu_buffer_copy_out")
	public static function copyOut(self:Int, offset:haxe.Int64, out:haxe.io.Bytes, len:Int):Bool;
	@:hlNative("xidl", "gpu_buffer_copy_in")
	public static function copyIn(self:Int, offset:haxe.Int64, data:haxe.io.Bytes, len:Int):Bool;
	@:hlNative("xidl", "gpu_buffer_size")
	public static function size(self:Int):haxe.Int64;
	@:hlNative("xidl", "gpu_buffer_usage")
	public static function usage(self:Int):Int;
	@:hlNative("xidl", "gpu_buffer_unmap")
	public static function unmap(self:Int):Void;
	@:hlNative("xidl", "gpu_buffer_destroy")
	public static function destroy(self:Int):Void;
}
