// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuBlasAabbGeometry(hl.Abstract<"xgpu_GpuBlasAabbGeometry">) {
	public inline function new(size:GpuBlasAabbGeometrySize, aabbBuffer:GpuBuffer, stride:haxe.Int64) this = GpuBlasAabbGeometryNative.create(size, aabbBuffer, stride);
	public inline function primitiveOffset(value:Int):Void GpuBlasAabbGeometryNative.primitiveOffset(this, value);
}

private extern class GpuBlasAabbGeometryNative {
	@:hlNative("xgpu", "gpu_blas_aabb_geometry_new")
	public static function create(size:GpuBlasAabbGeometrySize, aabbBuffer:GpuBuffer, stride:haxe.Int64):hl.Abstract<"xgpu_GpuBlasAabbGeometry">;
	@:hlNative("xgpu", "gpu_blas_aabb_geometry_primitive_offset")
	public static function primitiveOffset(self:hl.Abstract<"xgpu_GpuBlasAabbGeometry">, value:Int):Void;
}
