// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuBindGroupLayoutDescriptor(hl.Abstract<"xidl_GpuBindGroupLayoutDescriptor">) {
	public inline function new() this = GpuBindGroupLayoutDescriptorNative.create();
	public inline function label(value:String):Void GpuBindGroupLayoutDescriptorNative.label(this, value);
	public inline function addEntries(value:GpuBindGroupLayoutEntry):Void GpuBindGroupLayoutDescriptorNative.addEntries(this, value);
}

private extern class GpuBindGroupLayoutDescriptorNative {
	@:hlNative("xidl", "gpu_bind_group_layout_descriptor_new")
	public static function create():hl.Abstract<"xidl_GpuBindGroupLayoutDescriptor">;
	@:hlNative("xidl", "gpu_bind_group_layout_descriptor_label")
	public static function label(self:hl.Abstract<"xidl_GpuBindGroupLayoutDescriptor">, value:String):Void;
	@:hlNative("xidl", "gpu_bind_group_layout_descriptor_add_entries")
	public static function addEntries(self:hl.Abstract<"xidl_GpuBindGroupLayoutDescriptor">, value:GpuBindGroupLayoutEntry):Void;
}
