// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuBlasBuildEntry(hl.Abstract<"xgpu_GpuBlasBuildEntry">) {
	public inline function new(blas:GpuBlas) this = GpuBlasBuildEntryNative.create(blas);
	public inline function addTriangles(value:GpuBlasTriangleGeometry):Void GpuBlasBuildEntryNative.addTriangles(this, value);
	public inline function addAabbs(value:GpuBlasAabbGeometry):Void GpuBlasBuildEntryNative.addAabbs(this, value);
}

private extern class GpuBlasBuildEntryNative {
	@:hlNative("xgpu", "gpu_blas_build_entry_new")
	public static function create(blas:GpuBlas):hl.Abstract<"xgpu_GpuBlasBuildEntry">;
	@:hlNative("xgpu", "gpu_blas_build_entry_add_triangles")
	public static function addTriangles(self:hl.Abstract<"xgpu_GpuBlasBuildEntry">, value:GpuBlasTriangleGeometry):Void;
	@:hlNative("xgpu", "gpu_blas_build_entry_add_aabbs")
	public static function addAabbs(self:hl.Abstract<"xgpu_GpuBlasBuildEntry">, value:GpuBlasAabbGeometry):Void;
}
