// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuBlasTriangleGeometrySize(hl.Abstract<"xgpu_GpuBlasTriangleGeometrySize">) {
	public inline function new(vertexFormat:VertexFormat, vertexCount:Int) this = GpuBlasTriangleGeometrySizeNative.create(vertexFormat, vertexCount);
	public inline function indexFormat(value:IndexFormat):Void GpuBlasTriangleGeometrySizeNative.indexFormat(this, value);
	public inline function indexCount(value:Int):Void GpuBlasTriangleGeometrySizeNative.indexCount(this, value);
	public inline function flags(value:Int):Void GpuBlasTriangleGeometrySizeNative.flags(this, value);
}

private extern class GpuBlasTriangleGeometrySizeNative {
	@:hlNative("xgpu", "gpu_blas_triangle_geometry_size_new")
	public static function create(vertexFormat:VertexFormat, vertexCount:Int):hl.Abstract<"xgpu_GpuBlasTriangleGeometrySize">;
	@:hlNative("xgpu", "gpu_blas_triangle_geometry_size_index_format")
	public static function indexFormat(self:hl.Abstract<"xgpu_GpuBlasTriangleGeometrySize">, value:IndexFormat):Void;
	@:hlNative("xgpu", "gpu_blas_triangle_geometry_size_index_count")
	public static function indexCount(self:hl.Abstract<"xgpu_GpuBlasTriangleGeometrySize">, value:Int):Void;
	@:hlNative("xgpu", "gpu_blas_triangle_geometry_size_flags")
	public static function flags(self:hl.Abstract<"xgpu_GpuBlasTriangleGeometrySize">, value:Int):Void;
}
