// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuComputePassDescriptor(hl.Abstract<"xidl_GpuComputePassDescriptor">) {
	public inline function new() this = GpuComputePassDescriptorNative.create();
	public inline function label(value:String):Void GpuComputePassDescriptorNative.label(this, value);
	public inline function timestampWrites(value:GpuComputePassTimestampWrites):Void GpuComputePassDescriptorNative.timestampWrites(this, value);
}

private extern class GpuComputePassDescriptorNative {
	@:hlNative("xidl", "gpu_compute_pass_descriptor_new")
	public static function create():hl.Abstract<"xidl_GpuComputePassDescriptor">;
	@:hlNative("xidl", "gpu_compute_pass_descriptor_label")
	public static function label(self:hl.Abstract<"xidl_GpuComputePassDescriptor">, value:String):Void;
	@:hlNative("xidl", "gpu_compute_pass_descriptor_timestamp_writes")
	public static function timestampWrites(self:hl.Abstract<"xidl_GpuComputePassDescriptor">, value:GpuComputePassTimestampWrites):Void;
}
