// Generated by xgpu-bindgen. Do not edit by hand.
package gpu;

abstract GpuComputePipelineDescriptor(hl.Abstract<"xgpu_GpuComputePipelineDescriptor">) {
	public inline function new(compute:GpuProgrammableStage) this = GpuComputePipelineDescriptorNative.create(compute);
	public inline function label(value:String):Void GpuComputePipelineDescriptorNative.label(this, value);
	public inline function layout(value:GpuPipelineLayout):Void GpuComputePipelineDescriptorNative.layout(this, value);
	public inline function cache(value:GpuPipelineCache):Void GpuComputePipelineDescriptorNative.cache(this, value);
}

private extern class GpuComputePipelineDescriptorNative {
	@:hlNative("xgpu", "gpu_compute_pipeline_descriptor_new")
	public static function create(compute:GpuProgrammableStage):hl.Abstract<"xgpu_GpuComputePipelineDescriptor">;
	@:hlNative("xgpu", "gpu_compute_pipeline_descriptor_label")
	public static function label(self:hl.Abstract<"xgpu_GpuComputePipelineDescriptor">, value:String):Void;
	@:hlNative("xgpu", "gpu_compute_pipeline_descriptor_layout")
	public static function layout(self:hl.Abstract<"xgpu_GpuComputePipelineDescriptor">, value:GpuPipelineLayout):Void;
	@:hlNative("xgpu", "gpu_compute_pipeline_descriptor_cache")
	public static function cache(self:hl.Abstract<"xgpu_GpuComputePipelineDescriptor">, value:GpuPipelineCache):Void;
}
