// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuColor(hl.Abstract<"xidl_GpuColor">) {
	public inline function new(r:Float, g:Float, b:Float, a:Float) this = GpuColorNative.create(r, g, b, a);
}

private extern class GpuColorNative {
	@:hlNative("xidl", "gpu_color_new")
	public static function create(r:Float, g:Float, b:Float, a:Float):hl.Abstract<"xidl_GpuColor">;
}
