// Generated by xgpu-bindgen. Do not edit by hand.
package gpu;

abstract GpuCompilationInfo(Int) from Int to Int {
	public inline function valid():Bool return GpuCompilationInfoNative.valid(this);
	public inline function destroy():Void GpuCompilationInfoNative.destroy(this);
	public inline function messageCount():Int return GpuCompilationInfoNative.messageCount(this);
	public inline function message(index:Int):String { var value = GpuCompilationInfoNative.message(this, index); return value == null ? null : @:privateAccess String.fromUCS2(value); };
	public inline function messageType(index:Int):CompilationMessageType return GpuCompilationInfoNative.messageType(this, index);
	public inline function lineNum(index:Int):haxe.Int64 return GpuCompilationInfoNative.lineNum(this, index);
	public inline function linePos(index:Int):haxe.Int64 return GpuCompilationInfoNative.linePos(this, index);
	public inline function offset(index:Int):haxe.Int64 return GpuCompilationInfoNative.offset(this, index);
	public inline function length(index:Int):haxe.Int64 return GpuCompilationInfoNative.length(this, index);
}

private extern class GpuCompilationInfoNative {
	@:hlNative("xgpu", "gpu_compilation_info_valid")
	public static function valid(self:Int):Bool;
	@:hlNative("xgpu", "gpu_compilation_info_destroy")
	public static function destroy(self:Int):Void;
	@:hlNative("xgpu", "gpu_compilation_info_message_count")
	public static function messageCount(self:Int):Int;
	@:hlNative("xgpu", "gpu_compilation_info_message")
	public static function message(self:Int, index:Int):hl.Bytes;
	@:hlNative("xgpu", "gpu_compilation_info_message_type")
	public static function messageType(self:Int, index:Int):CompilationMessageType;
	@:hlNative("xgpu", "gpu_compilation_info_line_num")
	public static function lineNum(self:Int, index:Int):haxe.Int64;
	@:hlNative("xgpu", "gpu_compilation_info_line_pos")
	public static function linePos(self:Int, index:Int):haxe.Int64;
	@:hlNative("xgpu", "gpu_compilation_info_offset")
	public static function offset(self:Int, index:Int):haxe.Int64;
	@:hlNative("xgpu", "gpu_compilation_info_length")
	public static function length(self:Int, index:Int):haxe.Int64;
}
