// Generated by xgpu-bindgen. Do not edit by hand.
package gpu;

abstract GpuColorTargetState(hl.Abstract<"xgpu_GpuColorTargetState">) {
	public inline function new(format:TextureFormat) this = GpuColorTargetStateNative.create(format);
	public inline function blend(value:GpuBlendState):Void GpuColorTargetStateNative.blend(this, value);
	public inline function writeMask(value:Int):Void GpuColorTargetStateNative.writeMask(this, value);
}

private extern class GpuColorTargetStateNative {
	@:hlNative("xgpu", "gpu_color_target_state_new")
	public static function create(format:TextureFormat):hl.Abstract<"xgpu_GpuColorTargetState">;
	@:hlNative("xgpu", "gpu_color_target_state_blend")
	public static function blend(self:hl.Abstract<"xgpu_GpuColorTargetState">, value:GpuBlendState):Void;
	@:hlNative("xgpu", "gpu_color_target_state_write_mask")
	public static function writeMask(self:hl.Abstract<"xgpu_GpuColorTargetState">, value:Int):Void;
}
