// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuComputePassTimestampWrites(hl.Abstract<"xgpu_GpuComputePassTimestampWrites">) {
	public inline function new(querySet:GpuQuerySet) this = GpuComputePassTimestampWritesNative.create(querySet);
	public inline function beginningOfPassWriteIndex(value:Int):Void GpuComputePassTimestampWritesNative.beginningOfPassWriteIndex(this, value);
	public inline function endOfPassWriteIndex(value:Int):Void GpuComputePassTimestampWritesNative.endOfPassWriteIndex(this, value);
}

private extern class GpuComputePassTimestampWritesNative {
	@:hlNative("xgpu", "gpu_compute_pass_timestamp_writes_new")
	public static function create(querySet:GpuQuerySet):hl.Abstract<"xgpu_GpuComputePassTimestampWrites">;
	@:hlNative("xgpu", "gpu_compute_pass_timestamp_writes_beginning_of_pass_write_index")
	public static function beginningOfPassWriteIndex(self:hl.Abstract<"xgpu_GpuComputePassTimestampWrites">, value:Int):Void;
	@:hlNative("xgpu", "gpu_compute_pass_timestamp_writes_end_of_pass_write_index")
	public static function endOfPassWriteIndex(self:hl.Abstract<"xgpu_GpuComputePassTimestampWrites">, value:Int):Void;
}
