// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuDepthStencilState(hl.Abstract<"xidl_GpuDepthStencilState">) {
	public inline function new(format:TextureFormat) this = GpuDepthStencilStateNative.create(format);
	public inline function depthWriteEnabled(value:Bool):Void GpuDepthStencilStateNative.depthWriteEnabled(this, value);
	public inline function depthCompare(value:CompareFunction):Void GpuDepthStencilStateNative.depthCompare(this, value);
	public inline function stencilFront(value:GpuStencilFaceState):Void GpuDepthStencilStateNative.stencilFront(this, value);
	public inline function stencilBack(value:GpuStencilFaceState):Void GpuDepthStencilStateNative.stencilBack(this, value);
	public inline function stencilReadMask(value:Int):Void GpuDepthStencilStateNative.stencilReadMask(this, value);
	public inline function stencilWriteMask(value:Int):Void GpuDepthStencilStateNative.stencilWriteMask(this, value);
	public inline function depthBias(value:Int):Void GpuDepthStencilStateNative.depthBias(this, value);
	public inline function depthBiasSlopeScale(value:Float):Void GpuDepthStencilStateNative.depthBiasSlopeScale(this, value);
	public inline function depthBiasClamp(value:Float):Void GpuDepthStencilStateNative.depthBiasClamp(this, value);
}

private extern class GpuDepthStencilStateNative {
	@:hlNative("xidl", "gpu_depth_stencil_state_new")
	public static function create(format:TextureFormat):hl.Abstract<"xidl_GpuDepthStencilState">;
	@:hlNative("xidl", "gpu_depth_stencil_state_depth_write_enabled")
	public static function depthWriteEnabled(self:hl.Abstract<"xidl_GpuDepthStencilState">, value:Bool):Void;
	@:hlNative("xidl", "gpu_depth_stencil_state_depth_compare")
	public static function depthCompare(self:hl.Abstract<"xidl_GpuDepthStencilState">, value:CompareFunction):Void;
	@:hlNative("xidl", "gpu_depth_stencil_state_stencil_front")
	public static function stencilFront(self:hl.Abstract<"xidl_GpuDepthStencilState">, value:GpuStencilFaceState):Void;
	@:hlNative("xidl", "gpu_depth_stencil_state_stencil_back")
	public static function stencilBack(self:hl.Abstract<"xidl_GpuDepthStencilState">, value:GpuStencilFaceState):Void;
	@:hlNative("xidl", "gpu_depth_stencil_state_stencil_read_mask")
	public static function stencilReadMask(self:hl.Abstract<"xidl_GpuDepthStencilState">, value:Int):Void;
	@:hlNative("xidl", "gpu_depth_stencil_state_stencil_write_mask")
	public static function stencilWriteMask(self:hl.Abstract<"xidl_GpuDepthStencilState">, value:Int):Void;
	@:hlNative("xidl", "gpu_depth_stencil_state_depth_bias")
	public static function depthBias(self:hl.Abstract<"xidl_GpuDepthStencilState">, value:Int):Void;
	@:hlNative("xidl", "gpu_depth_stencil_state_depth_bias_slope_scale")
	public static function depthBiasSlopeScale(self:hl.Abstract<"xidl_GpuDepthStencilState">, value:Float):Void;
	@:hlNative("xidl", "gpu_depth_stencil_state_depth_bias_clamp")
	public static function depthBiasClamp(self:hl.Abstract<"xidl_GpuDepthStencilState">, value:Float):Void;
}
