// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuDeviceDescriptor(hl.Abstract<"xidl_GpuDeviceDescriptor">) {
	public inline function new() this = GpuDeviceDescriptorNative.create();
	public inline function addRequiredFeatures(value:Feature):Void GpuDeviceDescriptorNative.addRequiredFeatures(this, value);
	public inline function addRequiredLimits(key:Limit, value:haxe.Int64):Void GpuDeviceDescriptorNative.addRequiredLimits(this, key, value);
	public inline function addRequiredNativeFeatures(value:NativeFeature):Void GpuDeviceDescriptorNative.addRequiredNativeFeatures(this, value);
	public inline function addRequiredNativeLimits(key:NativeLimit, value:haxe.Int64):Void GpuDeviceDescriptorNative.addRequiredNativeLimits(this, key, value);
	public inline function memoryHints(value:MemoryHints):Void GpuDeviceDescriptorNative.memoryHints(this, value);
	public inline function experimentalFeatures(value:Bool):Void GpuDeviceDescriptorNative.experimentalFeatures(this, value);
	public inline function dontCareLoads(value:Bool):Void GpuDeviceDescriptorNative.dontCareLoads(this, value);
	public inline function trustedShaders(value:Bool):Void GpuDeviceDescriptorNative.trustedShaders(this, value);
	public inline function pipelineCacheData(value:Bool):Void GpuDeviceDescriptorNative.pipelineCacheData(this, value);
}

private extern class GpuDeviceDescriptorNative {
	@:hlNative("xidl", "gpu_device_descriptor_new")
	public static function create():hl.Abstract<"xidl_GpuDeviceDescriptor">;
	@:hlNative("xidl", "gpu_device_descriptor_add_required_features")
	public static function addRequiredFeatures(self:hl.Abstract<"xidl_GpuDeviceDescriptor">, value:Feature):Void;
	@:hlNative("xidl", "gpu_device_descriptor_add_required_limits")
	public static function addRequiredLimits(self:hl.Abstract<"xidl_GpuDeviceDescriptor">, key:Limit, value:haxe.Int64):Void;
	@:hlNative("xidl", "gpu_device_descriptor_add_required_native_features")
	public static function addRequiredNativeFeatures(self:hl.Abstract<"xidl_GpuDeviceDescriptor">, value:NativeFeature):Void;
	@:hlNative("xidl", "gpu_device_descriptor_add_required_native_limits")
	public static function addRequiredNativeLimits(self:hl.Abstract<"xidl_GpuDeviceDescriptor">, key:NativeLimit, value:haxe.Int64):Void;
	@:hlNative("xidl", "gpu_device_descriptor_memory_hints")
	public static function memoryHints(self:hl.Abstract<"xidl_GpuDeviceDescriptor">, value:MemoryHints):Void;
	@:hlNative("xidl", "gpu_device_descriptor_experimental_features")
	public static function experimentalFeatures(self:hl.Abstract<"xidl_GpuDeviceDescriptor">, value:Bool):Void;
	@:hlNative("xidl", "gpu_device_descriptor_dont_care_loads")
	public static function dontCareLoads(self:hl.Abstract<"xidl_GpuDeviceDescriptor">, value:Bool):Void;
	@:hlNative("xidl", "gpu_device_descriptor_trusted_shaders")
	public static function trustedShaders(self:hl.Abstract<"xidl_GpuDeviceDescriptor">, value:Bool):Void;
	@:hlNative("xidl", "gpu_device_descriptor_pipeline_cache_data")
	public static function pipelineCacheData(self:hl.Abstract<"xidl_GpuDeviceDescriptor">, value:Bool):Void;
}
