// Generated by xgpu-bindgen. Do not edit by hand.
package gpu;

abstract GpuDevice(Int) from Int to Int {
	public inline function valid():Bool return GpuDeviceNative.valid(this);
	public inline function takeError():String { var value = GpuDeviceNative.takeError(this); return value == null ? null : @:privateAccess String.fromUCS2(value); };
	public inline function queue():GpuQueue return GpuDeviceNative.queue(this);
	public inline function poll():Void GpuDeviceNative.poll(this);
	public inline function limit(which:Limit):haxe.Int64 return GpuDeviceNative.limit(this, which);
	public inline function supports(feature:Feature):Bool return GpuDeviceNative.supports(this, feature);
	public inline function destroy():Void GpuDeviceNative.destroy(this);
	public inline function createBuffer(descriptor:GpuBufferDescriptor):GpuBuffer return GpuDeviceNative.createBuffer(this, descriptor);
	public inline function mapBuffer(buffer:GpuBuffer, offset:haxe.Int64, size:haxe.Int64):ash.Future<Void> return GpuDeviceNative.mapBuffer(this, buffer, offset, size);
	public inline function mapBufferWith(buffer:GpuBuffer, mode:Int, offset:haxe.Int64, size:haxe.Int64):ash.Future<Void> return GpuDeviceNative.mapBufferWith(this, buffer, mode, offset, size);
	public inline function createShader(wgsl:String):GpuShader return GpuDeviceNative.createShader(this, wgsl);
	public inline function createShaderModule(descriptor:GpuShaderModuleDescriptor):GpuShader return GpuDeviceNative.createShaderModule(this, descriptor);
	public inline function createShaderPassthrough(descriptor:GpuPassthroughShaderDescriptor):GpuShader return GpuDeviceNative.createShaderPassthrough(this, descriptor);
	public inline function computePipeline(shader:GpuShader, entry:String):GpuPipeline return GpuDeviceNative.computePipeline(this, shader, entry);
	public inline function bindGroup(pipeline:GpuPipeline, group:Int, bindings:GpuBindings):GpuBindGroup return GpuDeviceNative.bindGroup(this, pipeline, group, bindings);
	public inline function encoder():GpuEncoder return GpuDeviceNative.encoder(this);
	public inline function queueWorkDone(queue:GpuQueue):ash.Future<Void> return GpuDeviceNative.queueWorkDone(this, queue);
	public inline function texture(descriptor:GpuTextureDescriptor):GpuTexture return GpuDeviceNative.texture(this, descriptor);
	public inline function pipeline():GpuPipelineBuilder return GpuDeviceNative.pipeline(this);
	public inline function sampler(descriptor:GpuSamplerDescriptor):GpuSampler return GpuDeviceNative.sampler(this, descriptor);
	public inline function createBindGroupLayout(descriptor:GpuBindGroupLayoutDescriptor):GpuBindGroupLayout return GpuDeviceNative.createBindGroupLayout(this, descriptor);
	public inline function createPipelineLayout(descriptor:GpuPipelineLayoutDescriptor):GpuPipelineLayout return GpuDeviceNative.createPipelineLayout(this, descriptor);
	public inline function createBindGroup(descriptor:GpuBindGroupDescriptor):GpuBindGroup return GpuDeviceNative.createBindGroup(this, descriptor);
	public inline function createComputePipeline(descriptor:GpuComputePipelineDescriptor):GpuPipeline return GpuDeviceNative.createComputePipeline(this, descriptor);
	public inline function createComputePipelineAsync(descriptor:GpuComputePipelineDescriptor):ash.Future<GpuPipeline> return GpuDeviceNative.createComputePipelineAsync(this, descriptor);
	public inline function createRenderPipeline(descriptor:GpuRenderPipelineDescriptor):GpuPipeline return GpuDeviceNative.createRenderPipeline(this, descriptor);
	public inline function createRenderPipelineAsync(descriptor:GpuRenderPipelineDescriptor):ash.Future<GpuPipeline> return GpuDeviceNative.createRenderPipelineAsync(this, descriptor);
	public inline function createQuerySet(descriptor:GpuQuerySetDescriptor):GpuQuerySet return GpuDeviceNative.createQuerySet(this, descriptor);
	public inline function createRenderBundleEncoder(descriptor:GpuRenderBundleEncoderDescriptor):GpuRenderBundleEncoder return GpuDeviceNative.createRenderBundleEncoder(this, descriptor);
	public inline function supportsNative(feature:NativeFeature):Bool return GpuDeviceNative.supportsNative(this, feature);
	public inline function nativeLimit(which:NativeLimit):haxe.Int64 return GpuDeviceNative.nativeLimit(this, which);
	public inline function pushErrorScope(filter:ErrorFilter):Void GpuDeviceNative.pushErrorScope(this, filter);
	public inline function popErrorScope():ash.Future<GpuError> return GpuDeviceNative.popErrorScope(this);
	public inline function lost():ash.Future<GpuDeviceLostInfo> return GpuDeviceNative.lost(this);
	public inline function createMeshPipeline(descriptor:GpuMeshPipelineDescriptor):GpuPipeline return GpuDeviceNative.createMeshPipeline(this, descriptor);
	public inline function createMeshPipelineAsync(descriptor:GpuMeshPipelineDescriptor):ash.Future<GpuPipeline> return GpuDeviceNative.createMeshPipelineAsync(this, descriptor);
	public inline function createExternalTexture(descriptor:GpuExternalTextureDescriptor):GpuExternalTexture return GpuDeviceNative.createExternalTexture(this, descriptor);
	public inline function createBlas(descriptor:GpuBlasDescriptor):GpuBlas return GpuDeviceNative.createBlas(this, descriptor);
	public inline function createTlas(descriptor:GpuTlasDescriptor):GpuTlas return GpuDeviceNative.createTlas(this, descriptor);
	public inline function createPipelineCache(descriptor:GpuPipelineCacheDescriptor):GpuPipelineCache return GpuDeviceNative.createPipelineCache(this, descriptor);
	public inline function configureSurfaceWith(surface:GpuSurface, configuration:GpuSurfaceConfiguration):Void GpuDeviceNative.configureSurfaceWith(this, surface, configuration);
	public inline function configureSurface(surface:GpuSurface, width:Int, height:Int, format:TextureFormat):Void GpuDeviceNative.configureSurface(this, surface, width, height, format);
}

private extern class GpuDeviceNative {
	@:hlNative("xgpu", "gpu_device_valid")
	public static function valid(self:Int):Bool;
	@:hlNative("xgpu", "gpu_device_take_error")
	public static function takeError(self:Int):hl.Bytes;
	@:hlNative("xgpu", "gpu_device_queue")
	public static function queue(self:Int):GpuQueue;
	@:hlNative("xgpu", "gpu_device_poll")
	public static function poll(self:Int):Void;
	@:hlNative("xgpu", "gpu_device_limit")
	public static function limit(self:Int, which:Limit):haxe.Int64;
	@:hlNative("xgpu", "gpu_device_supports")
	public static function supports(self:Int, feature:Feature):Bool;
	@:hlNative("xgpu", "gpu_device_destroy")
	public static function destroy(self:Int):Void;
	@:hlNative("xgpu", "gpu_device_create_buffer")
	public static function createBuffer(self:Int, descriptor:GpuBufferDescriptor):GpuBuffer;
	@:hlNative("xgpu", "gpu_device_map_buffer")
	public static function mapBuffer(self:Int, buffer:GpuBuffer, offset:haxe.Int64, size:haxe.Int64):ash.Future<Void>;
	@:hlNative("xgpu", "gpu_device_map_buffer_with")
	public static function mapBufferWith(self:Int, buffer:GpuBuffer, mode:Int, offset:haxe.Int64, size:haxe.Int64):ash.Future<Void>;
	@:hlNative("xgpu", "gpu_device_create_shader")
	public static function createShader(self:Int, wgsl:String):GpuShader;
	@:hlNative("xgpu", "gpu_device_create_shader_module")
	public static function createShaderModule(self:Int, descriptor:GpuShaderModuleDescriptor):GpuShader;
	@:hlNative("xgpu", "gpu_device_create_shader_passthrough")
	public static function createShaderPassthrough(self:Int, descriptor:GpuPassthroughShaderDescriptor):GpuShader;
	@:hlNative("xgpu", "gpu_device_compute_pipeline")
	public static function computePipeline(self:Int, shader:GpuShader, entry:String):GpuPipeline;
	@:hlNative("xgpu", "gpu_device_bind_group")
	public static function bindGroup(self:Int, pipeline:GpuPipeline, group:Int, bindings:GpuBindings):GpuBindGroup;
	@:hlNative("xgpu", "gpu_device_encoder")
	public static function encoder(self:Int):GpuEncoder;
	@:hlNative("xgpu", "gpu_device_queue_work_done")
	public static function queueWorkDone(self:Int, queue:GpuQueue):ash.Future<Void>;
	@:hlNative("xgpu", "gpu_device_texture")
	public static function texture(self:Int, descriptor:GpuTextureDescriptor):GpuTexture;
	@:hlNative("xgpu", "gpu_device_pipeline")
	public static function pipeline(self:Int):GpuPipelineBuilder;
	@:hlNative("xgpu", "gpu_device_sampler")
	public static function sampler(self:Int, descriptor:GpuSamplerDescriptor):GpuSampler;
	@:hlNative("xgpu", "gpu_device_create_bind_group_layout")
	public static function createBindGroupLayout(self:Int, descriptor:GpuBindGroupLayoutDescriptor):GpuBindGroupLayout;
	@:hlNative("xgpu", "gpu_device_create_pipeline_layout")
	public static function createPipelineLayout(self:Int, descriptor:GpuPipelineLayoutDescriptor):GpuPipelineLayout;
	@:hlNative("xgpu", "gpu_device_create_bind_group")
	public static function createBindGroup(self:Int, descriptor:GpuBindGroupDescriptor):GpuBindGroup;
	@:hlNative("xgpu", "gpu_device_create_compute_pipeline")
	public static function createComputePipeline(self:Int, descriptor:GpuComputePipelineDescriptor):GpuPipeline;
	@:hlNative("xgpu", "gpu_device_create_compute_pipeline_async")
	public static function createComputePipelineAsync(self:Int, descriptor:GpuComputePipelineDescriptor):ash.Future<GpuPipeline>;
	@:hlNative("xgpu", "gpu_device_create_render_pipeline")
	public static function createRenderPipeline(self:Int, descriptor:GpuRenderPipelineDescriptor):GpuPipeline;
	@:hlNative("xgpu", "gpu_device_create_render_pipeline_async")
	public static function createRenderPipelineAsync(self:Int, descriptor:GpuRenderPipelineDescriptor):ash.Future<GpuPipeline>;
	@:hlNative("xgpu", "gpu_device_create_query_set")
	public static function createQuerySet(self:Int, descriptor:GpuQuerySetDescriptor):GpuQuerySet;
	@:hlNative("xgpu", "gpu_device_create_render_bundle_encoder")
	public static function createRenderBundleEncoder(self:Int, descriptor:GpuRenderBundleEncoderDescriptor):GpuRenderBundleEncoder;
	@:hlNative("xgpu", "gpu_device_supports_native")
	public static function supportsNative(self:Int, feature:NativeFeature):Bool;
	@:hlNative("xgpu", "gpu_device_native_limit")
	public static function nativeLimit(self:Int, which:NativeLimit):haxe.Int64;
	@:hlNative("xgpu", "gpu_device_push_error_scope")
	public static function pushErrorScope(self:Int, filter:ErrorFilter):Void;
	@:hlNative("xgpu", "gpu_device_pop_error_scope")
	public static function popErrorScope(self:Int):ash.Future<GpuError>;
	@:hlNative("xgpu", "gpu_device_lost")
	public static function lost(self:Int):ash.Future<GpuDeviceLostInfo>;
	@:hlNative("xgpu", "gpu_device_create_mesh_pipeline")
	public static function createMeshPipeline(self:Int, descriptor:GpuMeshPipelineDescriptor):GpuPipeline;
	@:hlNative("xgpu", "gpu_device_create_mesh_pipeline_async")
	public static function createMeshPipelineAsync(self:Int, descriptor:GpuMeshPipelineDescriptor):ash.Future<GpuPipeline>;
	@:hlNative("xgpu", "gpu_device_create_external_texture")
	public static function createExternalTexture(self:Int, descriptor:GpuExternalTextureDescriptor):GpuExternalTexture;
	@:hlNative("xgpu", "gpu_device_create_blas")
	public static function createBlas(self:Int, descriptor:GpuBlasDescriptor):GpuBlas;
	@:hlNative("xgpu", "gpu_device_create_tlas")
	public static function createTlas(self:Int, descriptor:GpuTlasDescriptor):GpuTlas;
	@:hlNative("xgpu", "gpu_device_create_pipeline_cache")
	public static function createPipelineCache(self:Int, descriptor:GpuPipelineCacheDescriptor):GpuPipelineCache;
	@:hlNative("xgpu", "gpu_device_configure_surface_with")
	public static function configureSurfaceWith(self:Int, surface:GpuSurface, configuration:GpuSurfaceConfiguration):Void;
	@:hlNative("xgpu", "gpu_device_configure_surface")
	public static function configureSurface(self:Int, surface:GpuSurface, width:Int, height:Int, format:TextureFormat):Void;
}
