// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuDeviceLostInfo(Int) from Int to Int {
	public inline function valid():Bool return GpuDeviceLostInfoNative.valid(this);
	public inline function destroy():Void GpuDeviceLostInfoNative.destroy(this);
	public inline function reason():DeviceLostReason return GpuDeviceLostInfoNative.reason(this);
	public inline function message():String { var value = GpuDeviceLostInfoNative.message(this); return value == null ? null : @:privateAccess String.fromUCS2(value); };
}

private extern class GpuDeviceLostInfoNative {
	@:hlNative("xgpu", "gpu_device_lost_info_valid")
	public static function valid(self:Int):Bool;
	@:hlNative("xgpu", "gpu_device_lost_info_destroy")
	public static function destroy(self:Int):Void;
	@:hlNative("xgpu", "gpu_device_lost_info_reason")
	public static function reason(self:Int):DeviceLostReason;
	@:hlNative("xgpu", "gpu_device_lost_info_message")
	public static function message(self:Int):hl.Bytes;
}
