// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuError(Int) from Int to Int {
	public inline function valid():Bool return GpuErrorNative.valid(this);
	public inline function destroy():Void GpuErrorNative.destroy(this);
	public inline function filter():ErrorFilter return GpuErrorNative.filter(this);
	public inline function message():String { var value = GpuErrorNative.message(this); return value == null ? null : @:privateAccess String.fromUCS2(value); };
}

private extern class GpuErrorNative {
	@:hlNative("xidl", "gpu_error_valid")
	public static function valid(self:Int):Bool;
	@:hlNative("xidl", "gpu_error_destroy")
	public static function destroy(self:Int):Void;
	@:hlNative("xidl", "gpu_error_filter")
	public static function filter(self:Int):ErrorFilter;
	@:hlNative("xidl", "gpu_error_message")
	public static function message(self:Int):hl.Bytes;
}
