// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuExternalTextureDescriptor(hl.Abstract<"xgpu_GpuExternalTextureDescriptor">) {
	public inline function new(format:ExternalTextureFormat) this = GpuExternalTextureDescriptorNative.create(format);
	public inline function addPlanes(value:GpuTextureView):Void GpuExternalTextureDescriptorNative.addPlanes(this, value);
	public inline function label(value:String):Void GpuExternalTextureDescriptorNative.label(this, value);
	public inline function width(value:Int):Void GpuExternalTextureDescriptorNative.width(this, value);
	public inline function height(value:Int):Void GpuExternalTextureDescriptorNative.height(this, value);
	public inline function addYuvConversionMatrix(value:Float):Void GpuExternalTextureDescriptorNative.addYuvConversionMatrix(this, value);
	public inline function addGamutConversionMatrix(value:Float):Void GpuExternalTextureDescriptorNative.addGamutConversionMatrix(this, value);
	public inline function addSampleTransform(value:Float):Void GpuExternalTextureDescriptorNative.addSampleTransform(this, value);
	public inline function addLoadTransform(value:Float):Void GpuExternalTextureDescriptorNative.addLoadTransform(this, value);
	public inline function srcTransferFunction(value:GpuExternalTextureTransferFunction):Void GpuExternalTextureDescriptorNative.srcTransferFunction(this, value);
	public inline function dstTransferFunction(value:GpuExternalTextureTransferFunction):Void GpuExternalTextureDescriptorNative.dstTransferFunction(this, value);
}

private extern class GpuExternalTextureDescriptorNative {
	@:hlNative("xgpu", "gpu_external_texture_descriptor_new")
	public static function create(format:ExternalTextureFormat):hl.Abstract<"xgpu_GpuExternalTextureDescriptor">;
	@:hlNative("xgpu", "gpu_external_texture_descriptor_add_planes")
	public static function addPlanes(self:hl.Abstract<"xgpu_GpuExternalTextureDescriptor">, value:GpuTextureView):Void;
	@:hlNative("xgpu", "gpu_external_texture_descriptor_label")
	public static function label(self:hl.Abstract<"xgpu_GpuExternalTextureDescriptor">, value:String):Void;
	@:hlNative("xgpu", "gpu_external_texture_descriptor_width")
	public static function width(self:hl.Abstract<"xgpu_GpuExternalTextureDescriptor">, value:Int):Void;
	@:hlNative("xgpu", "gpu_external_texture_descriptor_height")
	public static function height(self:hl.Abstract<"xgpu_GpuExternalTextureDescriptor">, value:Int):Void;
	@:hlNative("xgpu", "gpu_external_texture_descriptor_add_yuv_conversion_matrix")
	public static function addYuvConversionMatrix(self:hl.Abstract<"xgpu_GpuExternalTextureDescriptor">, value:Float):Void;
	@:hlNative("xgpu", "gpu_external_texture_descriptor_add_gamut_conversion_matrix")
	public static function addGamutConversionMatrix(self:hl.Abstract<"xgpu_GpuExternalTextureDescriptor">, value:Float):Void;
	@:hlNative("xgpu", "gpu_external_texture_descriptor_add_sample_transform")
	public static function addSampleTransform(self:hl.Abstract<"xgpu_GpuExternalTextureDescriptor">, value:Float):Void;
	@:hlNative("xgpu", "gpu_external_texture_descriptor_add_load_transform")
	public static function addLoadTransform(self:hl.Abstract<"xgpu_GpuExternalTextureDescriptor">, value:Float):Void;
	@:hlNative("xgpu", "gpu_external_texture_descriptor_src_transfer_function")
	public static function srcTransferFunction(self:hl.Abstract<"xgpu_GpuExternalTextureDescriptor">, value:GpuExternalTextureTransferFunction):Void;
	@:hlNative("xgpu", "gpu_external_texture_descriptor_dst_transfer_function")
	public static function dstTransferFunction(self:hl.Abstract<"xgpu_GpuExternalTextureDescriptor">, value:GpuExternalTextureTransferFunction):Void;
}
