// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuExternalTexture(Int) from Int to Int {
	public inline function valid():Bool return GpuExternalTextureNative.valid(this);
	public inline function destroy():Void GpuExternalTextureNative.destroy(this);
}

private extern class GpuExternalTextureNative {
	@:hlNative("xidl", "gpu_external_texture_valid")
	public static function valid(self:Int):Bool;
	@:hlNative("xidl", "gpu_external_texture_destroy")
	public static function destroy(self:Int):Void;
}
