// Generated by xgpu-bindgen. Do not edit by hand.
package gpu;

abstract GpuExternalTextureBindingLayout(hl.Abstract<"xgpu_GpuExternalTextureBindingLayout">) {
	public inline function new() this = GpuExternalTextureBindingLayoutNative.create();
}

private extern class GpuExternalTextureBindingLayoutNative {
	@:hlNative("xgpu", "gpu_external_texture_binding_layout_new")
	public static function create():hl.Abstract<"xgpu_GpuExternalTextureBindingLayout">;
}
