// Generated by xgpu-bindgen. Do not edit by hand.
package gpu;

abstract GpuExtent3D(hl.Abstract<"xgpu_GpuExtent3D">) {
	public inline function new(width:Int) this = GpuExtent3DNative.create(width);
	public inline function height(value:Int):Void GpuExtent3DNative.height(this, value);
	public inline function depthOrArrayLayers(value:Int):Void GpuExtent3DNative.depthOrArrayLayers(this, value);
}

private extern class GpuExtent3DNative {
	@:hlNative("xgpu", "gpu_extent3_d_new")
	public static function create(width:Int):hl.Abstract<"xgpu_GpuExtent3D">;
	@:hlNative("xgpu", "gpu_extent3_d_height")
	public static function height(self:hl.Abstract<"xgpu_GpuExtent3D">, value:Int):Void;
	@:hlNative("xgpu", "gpu_extent3_d_depth_or_array_layers")
	public static function depthOrArrayLayers(self:hl.Abstract<"xgpu_GpuExtent3D">, value:Int):Void;
}
