// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuExternalTextureTransferFunction(hl.Abstract<"xgpu_GpuExternalTextureTransferFunction">) {
	public inline function new(a:Float, b:Float, g:Float, k:Float) this = GpuExternalTextureTransferFunctionNative.create(a, b, g, k);
}

private extern class GpuExternalTextureTransferFunctionNative {
	@:hlNative("xgpu", "gpu_external_texture_transfer_function_new")
	public static function create(a:Float, b:Float, g:Float, k:Float):hl.Abstract<"xgpu_GpuExternalTextureTransferFunction">;
}
