// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuEncoder(Int) from Int to Int {
	public inline function destroy():Void GpuEncoderNative.destroy(this);
	public inline function valid():Bool return GpuEncoderNative.valid(this);
	public inline function compute(pipeline:GpuPipeline, bindgroup:GpuBindGroup, x:Int, y:Int, z:Int):Void GpuEncoderNative.compute(this, pipeline, bindgroup, x, y, z);
	public inline function copyBuffer(src:GpuBuffer, src_offset:haxe.Int64, dst:GpuBuffer, dst_offset:haxe.Int64, size:haxe.Int64):Void GpuEncoderNative.copyBuffer(this, src, src_offset, dst, dst_offset, size);
	public inline function submit(queue:GpuQueue):Void GpuEncoderNative.submit(this, queue);
	public inline function passReset():Void GpuEncoderNative.passReset(this);
	public inline function passColour(view:GpuTextureView, r:Float, g:Float, b:Float, a:Float):Void GpuEncoderNative.passColour(this, view, r, g, b, a);
	public inline function passDepth(view:GpuTextureView, clear:Float, stencil_clear:Int):Void GpuEncoderNative.passDepth(this, view, clear, stencil_clear);
	public inline function passBegin():Void GpuEncoderNative.passBegin(this);
	public inline function renderSetPipeline(pipeline:GpuPipeline):Void GpuEncoderNative.renderSetPipeline(this, pipeline);
	public inline function renderSetVertexBuffer(slot:Int, buffer:GpuBuffer):Void GpuEncoderNative.renderSetVertexBuffer(this, slot, buffer);
	public inline function renderSetViewport(x:Float, y:Float, width:Float, height:Float, min_depth:Float, max_depth:Float):Void GpuEncoderNative.renderSetViewport(this, x, y, width, height, min_depth, max_depth);
	public inline function renderSetScissorRect(x:Int, y:Int, width:Int, height:Int):Void GpuEncoderNative.renderSetScissorRect(this, x, y, width, height);
	public inline function renderDraw(vertices:Int, instances:Int):Void GpuEncoderNative.renderDraw(this, vertices, instances);
	public inline function renderEnd():Void GpuEncoderNative.renderEnd(this);
	public inline function copyBufferToTexture(buffer:GpuBuffer, bytes_per_row:Int, texture:GpuTexture, width:Int, height:Int):Void GpuEncoderNative.copyBufferToTexture(this, buffer, bytes_per_row, texture, width, height);
	public inline function copyTextureToTexture(src:GpuTexture, dst:GpuTexture, width:Int, height:Int):Void GpuEncoderNative.copyTextureToTexture(this, src, dst, width, height);
	public inline function clearBuffer(buffer:GpuBuffer, offset:haxe.Int64, size:haxe.Int64):Void GpuEncoderNative.clearBuffer(this, buffer, offset, size);
	public inline function copyTextureToBuffer(texture:GpuTexture, buffer:GpuBuffer, width:Int, height:Int, bytes_per_row:Int):Void GpuEncoderNative.copyTextureToBuffer(this, texture, buffer, width, height, bytes_per_row);
	public inline function renderSetBindGroup(group:Int, bindgroup:GpuBindGroup):Void GpuEncoderNative.renderSetBindGroup(this, group, bindgroup);
	public inline function renderSetBindGroupOffsets(group:Int, bindgroup:GpuBindGroup, offsets:haxe.io.Bytes, start:haxe.Int64, count:Int):Void GpuEncoderNative.renderSetBindGroupOffsets(this, group, bindgroup, offsets, start, count);
	public inline function computeBegin():Void GpuEncoderNative.computeBegin(this);
	public inline function computeSetPipeline(pipeline:GpuPipeline):Void GpuEncoderNative.computeSetPipeline(this, pipeline);
	public inline function computeSetBindGroup(group:Int, bindgroup:GpuBindGroup):Void GpuEncoderNative.computeSetBindGroup(this, group, bindgroup);
	public inline function computeSetBindGroupOffsets(group:Int, bindgroup:GpuBindGroup, offsets:haxe.io.Bytes, start:haxe.Int64, count:Int):Void GpuEncoderNative.computeSetBindGroupOffsets(this, group, bindgroup, offsets, start, count);
	public inline function computeDispatch(x:Int, y:Int, z:Int):Void GpuEncoderNative.computeDispatch(this, x, y, z);
	public inline function computeDispatchIndirect(buffer:GpuBuffer, offset:haxe.Int64):Void GpuEncoderNative.computeDispatchIndirect(this, buffer, offset);
	public inline function computeEnd():Void GpuEncoderNative.computeEnd(this);
	public inline function beginRenderPass(descriptor:GpuRenderPassDescriptor):Void GpuEncoderNative.beginRenderPass(this, descriptor);
	public inline function beginComputePass(descriptor:GpuComputePassDescriptor):Void GpuEncoderNative.beginComputePass(this, descriptor);
	public inline function renderDrawRange(vertex_count:Int, instance_count:Int, first_vertex:Int, first_instance:Int):Void GpuEncoderNative.renderDrawRange(this, vertex_count, instance_count, first_vertex, first_instance);
	public inline function renderDrawIndexedRange(index_count:Int, instance_count:Int, first_index:Int, base_vertex:Int, first_instance:Int):Void GpuEncoderNative.renderDrawIndexedRange(this, index_count, instance_count, first_index, base_vertex, first_instance);
	public inline function renderSetVertexBufferRange(slot:Int, buffer:GpuBuffer, offset:haxe.Int64, size:haxe.Int64):Void GpuEncoderNative.renderSetVertexBufferRange(this, slot, buffer, offset, size);
	public inline function renderSetIndexBufferRange(buffer:GpuBuffer, format:IndexFormat, offset:haxe.Int64, size:haxe.Int64):Void GpuEncoderNative.renderSetIndexBufferRange(this, buffer, format, offset, size);
	public inline function renderMultiDrawIndirect(buffer:GpuBuffer, offset:haxe.Int64, count:Int):Void GpuEncoderNative.renderMultiDrawIndirect(this, buffer, offset, count);
	public inline function renderMultiDrawIndexedIndirect(buffer:GpuBuffer, offset:haxe.Int64, count:Int):Void GpuEncoderNative.renderMultiDrawIndexedIndirect(this, buffer, offset, count);
	public inline function renderMultiDrawIndirectCount(buffer:GpuBuffer, offset:haxe.Int64, count_buffer:GpuBuffer, count_offset:haxe.Int64, max_count:Int):Void GpuEncoderNative.renderMultiDrawIndirectCount(this, buffer, offset, count_buffer, count_offset, max_count);
	public inline function renderMultiDrawIndexedIndirectCount(buffer:GpuBuffer, offset:haxe.Int64, count_buffer:GpuBuffer, count_offset:haxe.Int64, max_count:Int):Void GpuEncoderNative.renderMultiDrawIndexedIndirectCount(this, buffer, offset, count_buffer, count_offset, max_count);
	public inline function renderSetImmediates(offset:Int, data:haxe.io.Bytes, start:haxe.Int64, size:Int):Void GpuEncoderNative.renderSetImmediates(this, offset, data, start, size);
	public inline function computeSetImmediates(offset:Int, data:haxe.io.Bytes, start:haxe.Int64, size:Int):Void GpuEncoderNative.computeSetImmediates(this, offset, data, start, size);
	public inline function renderBeginOcclusionQuery(index:Int):Void GpuEncoderNative.renderBeginOcclusionQuery(this, index);
	public inline function renderEndOcclusionQuery():Void GpuEncoderNative.renderEndOcclusionQuery(this);
	public inline function renderBeginPipelineStatisticsQuery(query_set:GpuQuerySet, index:Int):Void GpuEncoderNative.renderBeginPipelineStatisticsQuery(this, query_set, index);
	public inline function renderEndPipelineStatisticsQuery():Void GpuEncoderNative.renderEndPipelineStatisticsQuery(this);
	public inline function computeBeginPipelineStatisticsQuery(query_set:GpuQuerySet, index:Int):Void GpuEncoderNative.computeBeginPipelineStatisticsQuery(this, query_set, index);
	public inline function computeEndPipelineStatisticsQuery():Void GpuEncoderNative.computeEndPipelineStatisticsQuery(this);
	public inline function writeTimestamp(query_set:GpuQuerySet, index:Int):Void GpuEncoderNative.writeTimestamp(this, query_set, index);
	public inline function renderWriteTimestamp(query_set:GpuQuerySet, index:Int):Void GpuEncoderNative.renderWriteTimestamp(this, query_set, index);
	public inline function computeWriteTimestamp(query_set:GpuQuerySet, index:Int):Void GpuEncoderNative.computeWriteTimestamp(this, query_set, index);
	public inline function resolveQuerySet(query_set:GpuQuerySet, first:Int, count:Int, destination:GpuBuffer, offset:haxe.Int64):Void GpuEncoderNative.resolveQuerySet(this, query_set, first, count, destination, offset);
	public inline function renderExecuteBundle(bundle:GpuRenderBundle):Void GpuEncoderNative.renderExecuteBundle(this, bundle);
	public inline function renderDrawMeshTasks(x:Int, y:Int, z:Int):Void GpuEncoderNative.renderDrawMeshTasks(this, x, y, z);
	public inline function renderDrawMeshTasksIndirect(buffer:GpuBuffer, offset:haxe.Int64):Void GpuEncoderNative.renderDrawMeshTasksIndirect(this, buffer, offset);
	public inline function renderMultiDrawMeshTasksIndirect(buffer:GpuBuffer, offset:haxe.Int64, count:Int):Void GpuEncoderNative.renderMultiDrawMeshTasksIndirect(this, buffer, offset, count);
	public inline function renderMultiDrawMeshTasksIndirectCount(buffer:GpuBuffer, offset:haxe.Int64, count_buffer:GpuBuffer, count_offset:haxe.Int64, max_count:Int):Void GpuEncoderNative.renderMultiDrawMeshTasksIndirectCount(this, buffer, offset, count_buffer, count_offset, max_count);
	public inline function buildAccelerationStructures(build:GpuAccelerationStructureBuild):Void GpuEncoderNative.buildAccelerationStructures(this, build);
	public inline function copyBufferToTextureWith(source:GpuTexelCopyBufferInfo, destination:GpuTexelCopyTextureInfo, size:GpuExtent3D):Void GpuEncoderNative.copyBufferToTextureWith(this, source, destination, size);
	public inline function copyTextureToBufferWith(source:GpuTexelCopyTextureInfo, destination:GpuTexelCopyBufferInfo, size:GpuExtent3D):Void GpuEncoderNative.copyTextureToBufferWith(this, source, destination, size);
	public inline function copyTextureToTextureWith(source:GpuTexelCopyTextureInfo, destination:GpuTexelCopyTextureInfo, size:GpuExtent3D):Void GpuEncoderNative.copyTextureToTextureWith(this, source, destination, size);
	public inline function clearTexture(texture:GpuTexture):Void GpuEncoderNative.clearTexture(this, texture);
	public inline function renderSetIndexBuffer(buffer:GpuBuffer, format:IndexFormat):Void GpuEncoderNative.renderSetIndexBuffer(this, buffer, format);
	public inline function renderDrawIndexed(indices:Int, instances:Int):Void GpuEncoderNative.renderDrawIndexed(this, indices, instances);
	public inline function renderSetBlendConstant(r:Float, g:Float, b:Float, a:Float):Void GpuEncoderNative.renderSetBlendConstant(this, r, g, b, a);
	public inline function renderSetStencilReference(reference:Int):Void GpuEncoderNative.renderSetStencilReference(this, reference);
	public inline function computeIndirect(pipeline:GpuPipeline, bindgroup:GpuBindGroup, buffer:GpuBuffer, offset:haxe.Int64):Void GpuEncoderNative.computeIndirect(this, pipeline, bindgroup, buffer, offset);
	public inline function renderDrawIndirect(buffer:GpuBuffer, offset:haxe.Int64):Void GpuEncoderNative.renderDrawIndirect(this, buffer, offset);
	public inline function renderDrawIndexedIndirect(buffer:GpuBuffer, offset:haxe.Int64):Void GpuEncoderNative.renderDrawIndexedIndirect(this, buffer, offset);
	public inline function pushDebugGroup(label:String):Void GpuEncoderNative.pushDebugGroup(this, label);
	public inline function popDebugGroup():Void GpuEncoderNative.popDebugGroup(this);
	public inline function insertDebugMarker(label:String):Void GpuEncoderNative.insertDebugMarker(this, label);
}

private extern class GpuEncoderNative {
	@:hlNative("xidl", "gpu_encoder_destroy")
	public static function destroy(self:Int):Void;
	@:hlNative("xidl", "gpu_encoder_valid")
	public static function valid(self:Int):Bool;
	@:hlNative("xidl", "gpu_encoder_compute")
	public static function compute(self:Int, pipeline:GpuPipeline, bindgroup:GpuBindGroup, x:Int, y:Int, z:Int):Void;
	@:hlNative("xidl", "gpu_encoder_copy_buffer")
	public static function copyBuffer(self:Int, src:GpuBuffer, src_offset:haxe.Int64, dst:GpuBuffer, dst_offset:haxe.Int64, size:haxe.Int64):Void;
	@:hlNative("xidl", "gpu_encoder_submit")
	public static function submit(self:Int, queue:GpuQueue):Void;
	@:hlNative("xidl", "gpu_encoder_pass_reset")
	public static function passReset(self:Int):Void;
	@:hlNative("xidl", "gpu_encoder_pass_colour")
	public static function passColour(self:Int, view:GpuTextureView, r:Float, g:Float, b:Float, a:Float):Void;
	@:hlNative("xidl", "gpu_encoder_pass_depth")
	public static function passDepth(self:Int, view:GpuTextureView, clear:Float, stencil_clear:Int):Void;
	@:hlNative("xidl", "gpu_encoder_pass_begin")
	public static function passBegin(self:Int):Void;
	@:hlNative("xidl", "gpu_encoder_render_set_pipeline")
	public static function renderSetPipeline(self:Int, pipeline:GpuPipeline):Void;
	@:hlNative("xidl", "gpu_encoder_render_set_vertex_buffer")
	public static function renderSetVertexBuffer(self:Int, slot:Int, buffer:GpuBuffer):Void;
	@:hlNative("xidl", "gpu_encoder_render_set_viewport")
	public static function renderSetViewport(self:Int, x:Float, y:Float, width:Float, height:Float, min_depth:Float, max_depth:Float):Void;
	@:hlNative("xidl", "gpu_encoder_render_set_scissor_rect")
	public static function renderSetScissorRect(self:Int, x:Int, y:Int, width:Int, height:Int):Void;
	@:hlNative("xidl", "gpu_encoder_render_draw")
	public static function renderDraw(self:Int, vertices:Int, instances:Int):Void;
	@:hlNative("xidl", "gpu_encoder_render_end")
	public static function renderEnd(self:Int):Void;
	@:hlNative("xidl", "gpu_encoder_copy_buffer_to_texture")
	public static function copyBufferToTexture(self:Int, buffer:GpuBuffer, bytes_per_row:Int, texture:GpuTexture, width:Int, height:Int):Void;
	@:hlNative("xidl", "gpu_encoder_copy_texture_to_texture")
	public static function copyTextureToTexture(self:Int, src:GpuTexture, dst:GpuTexture, width:Int, height:Int):Void;
	@:hlNative("xidl", "gpu_encoder_clear_buffer")
	public static function clearBuffer(self:Int, buffer:GpuBuffer, offset:haxe.Int64, size:haxe.Int64):Void;
	@:hlNative("xidl", "gpu_encoder_copy_texture_to_buffer")
	public static function copyTextureToBuffer(self:Int, texture:GpuTexture, buffer:GpuBuffer, width:Int, height:Int, bytes_per_row:Int):Void;
	@:hlNative("xidl", "gpu_encoder_render_set_bind_group")
	public static function renderSetBindGroup(self:Int, group:Int, bindgroup:GpuBindGroup):Void;
	@:hlNative("xidl", "gpu_encoder_render_set_bind_group_offsets")
	public static function renderSetBindGroupOffsets(self:Int, group:Int, bindgroup:GpuBindGroup, offsets:haxe.io.Bytes, start:haxe.Int64, count:Int):Void;
	@:hlNative("xidl", "gpu_encoder_compute_begin")
	public static function computeBegin(self:Int):Void;
	@:hlNative("xidl", "gpu_encoder_compute_set_pipeline")
	public static function computeSetPipeline(self:Int, pipeline:GpuPipeline):Void;
	@:hlNative("xidl", "gpu_encoder_compute_set_bind_group")
	public static function computeSetBindGroup(self:Int, group:Int, bindgroup:GpuBindGroup):Void;
	@:hlNative("xidl", "gpu_encoder_compute_set_bind_group_offsets")
	public static function computeSetBindGroupOffsets(self:Int, group:Int, bindgroup:GpuBindGroup, offsets:haxe.io.Bytes, start:haxe.Int64, count:Int):Void;
	@:hlNative("xidl", "gpu_encoder_compute_dispatch")
	public static function computeDispatch(self:Int, x:Int, y:Int, z:Int):Void;
	@:hlNative("xidl", "gpu_encoder_compute_dispatch_indirect")
	public static function computeDispatchIndirect(self:Int, buffer:GpuBuffer, offset:haxe.Int64):Void;
	@:hlNative("xidl", "gpu_encoder_compute_end")
	public static function computeEnd(self:Int):Void;
	@:hlNative("xidl", "gpu_encoder_begin_render_pass")
	public static function beginRenderPass(self:Int, descriptor:GpuRenderPassDescriptor):Void;
	@:hlNative("xidl", "gpu_encoder_begin_compute_pass")
	public static function beginComputePass(self:Int, descriptor:GpuComputePassDescriptor):Void;
	@:hlNative("xidl", "gpu_encoder_render_draw_range")
	public static function renderDrawRange(self:Int, vertex_count:Int, instance_count:Int, first_vertex:Int, first_instance:Int):Void;
	@:hlNative("xidl", "gpu_encoder_render_draw_indexed_range")
	public static function renderDrawIndexedRange(self:Int, index_count:Int, instance_count:Int, first_index:Int, base_vertex:Int, first_instance:Int):Void;
	@:hlNative("xidl", "gpu_encoder_render_set_vertex_buffer_range")
	public static function renderSetVertexBufferRange(self:Int, slot:Int, buffer:GpuBuffer, offset:haxe.Int64, size:haxe.Int64):Void;
	@:hlNative("xidl", "gpu_encoder_render_set_index_buffer_range")
	public static function renderSetIndexBufferRange(self:Int, buffer:GpuBuffer, format:IndexFormat, offset:haxe.Int64, size:haxe.Int64):Void;
	@:hlNative("xidl", "gpu_encoder_render_multi_draw_indirect")
	public static function renderMultiDrawIndirect(self:Int, buffer:GpuBuffer, offset:haxe.Int64, count:Int):Void;
	@:hlNative("xidl", "gpu_encoder_render_multi_draw_indexed_indirect")
	public static function renderMultiDrawIndexedIndirect(self:Int, buffer:GpuBuffer, offset:haxe.Int64, count:Int):Void;
	@:hlNative("xidl", "gpu_encoder_render_multi_draw_indirect_count")
	public static function renderMultiDrawIndirectCount(self:Int, buffer:GpuBuffer, offset:haxe.Int64, count_buffer:GpuBuffer, count_offset:haxe.Int64, max_count:Int):Void;
	@:hlNative("xidl", "gpu_encoder_render_multi_draw_indexed_indirect_count")
	public static function renderMultiDrawIndexedIndirectCount(self:Int, buffer:GpuBuffer, offset:haxe.Int64, count_buffer:GpuBuffer, count_offset:haxe.Int64, max_count:Int):Void;
	@:hlNative("xidl", "gpu_encoder_render_set_immediates")
	public static function renderSetImmediates(self:Int, offset:Int, data:haxe.io.Bytes, start:haxe.Int64, size:Int):Void;
	@:hlNative("xidl", "gpu_encoder_compute_set_immediates")
	public static function computeSetImmediates(self:Int, offset:Int, data:haxe.io.Bytes, start:haxe.Int64, size:Int):Void;
	@:hlNative("xidl", "gpu_encoder_render_begin_occlusion_query")
	public static function renderBeginOcclusionQuery(self:Int, index:Int):Void;
	@:hlNative("xidl", "gpu_encoder_render_end_occlusion_query")
	public static function renderEndOcclusionQuery(self:Int):Void;
	@:hlNative("xidl", "gpu_encoder_render_begin_pipeline_statistics_query")
	public static function renderBeginPipelineStatisticsQuery(self:Int, query_set:GpuQuerySet, index:Int):Void;
	@:hlNative("xidl", "gpu_encoder_render_end_pipeline_statistics_query")
	public static function renderEndPipelineStatisticsQuery(self:Int):Void;
	@:hlNative("xidl", "gpu_encoder_compute_begin_pipeline_statistics_query")
	public static function computeBeginPipelineStatisticsQuery(self:Int, query_set:GpuQuerySet, index:Int):Void;
	@:hlNative("xidl", "gpu_encoder_compute_end_pipeline_statistics_query")
	public static function computeEndPipelineStatisticsQuery(self:Int):Void;
	@:hlNative("xidl", "gpu_encoder_write_timestamp")
	public static function writeTimestamp(self:Int, query_set:GpuQuerySet, index:Int):Void;
	@:hlNative("xidl", "gpu_encoder_render_write_timestamp")
	public static function renderWriteTimestamp(self:Int, query_set:GpuQuerySet, index:Int):Void;
	@:hlNative("xidl", "gpu_encoder_compute_write_timestamp")
	public static function computeWriteTimestamp(self:Int, query_set:GpuQuerySet, index:Int):Void;
	@:hlNative("xidl", "gpu_encoder_resolve_query_set")
	public static function resolveQuerySet(self:Int, query_set:GpuQuerySet, first:Int, count:Int, destination:GpuBuffer, offset:haxe.Int64):Void;
	@:hlNative("xidl", "gpu_encoder_render_execute_bundle")
	public static function renderExecuteBundle(self:Int, bundle:GpuRenderBundle):Void;
	@:hlNative("xidl", "gpu_encoder_render_draw_mesh_tasks")
	public static function renderDrawMeshTasks(self:Int, x:Int, y:Int, z:Int):Void;
	@:hlNative("xidl", "gpu_encoder_render_draw_mesh_tasks_indirect")
	public static function renderDrawMeshTasksIndirect(self:Int, buffer:GpuBuffer, offset:haxe.Int64):Void;
	@:hlNative("xidl", "gpu_encoder_render_multi_draw_mesh_tasks_indirect")
	public static function renderMultiDrawMeshTasksIndirect(self:Int, buffer:GpuBuffer, offset:haxe.Int64, count:Int):Void;
	@:hlNative("xidl", "gpu_encoder_render_multi_draw_mesh_tasks_indirect_count")
	public static function renderMultiDrawMeshTasksIndirectCount(self:Int, buffer:GpuBuffer, offset:haxe.Int64, count_buffer:GpuBuffer, count_offset:haxe.Int64, max_count:Int):Void;
	@:hlNative("xidl", "gpu_encoder_build_acceleration_structures")
	public static function buildAccelerationStructures(self:Int, build:GpuAccelerationStructureBuild):Void;
	@:hlNative("xidl", "gpu_encoder_copy_buffer_to_texture_with")
	public static function copyBufferToTextureWith(self:Int, source:GpuTexelCopyBufferInfo, destination:GpuTexelCopyTextureInfo, size:GpuExtent3D):Void;
	@:hlNative("xidl", "gpu_encoder_copy_texture_to_buffer_with")
	public static function copyTextureToBufferWith(self:Int, source:GpuTexelCopyTextureInfo, destination:GpuTexelCopyBufferInfo, size:GpuExtent3D):Void;
	@:hlNative("xidl", "gpu_encoder_copy_texture_to_texture_with")
	public static function copyTextureToTextureWith(self:Int, source:GpuTexelCopyTextureInfo, destination:GpuTexelCopyTextureInfo, size:GpuExtent3D):Void;
	@:hlNative("xidl", "gpu_encoder_clear_texture")
	public static function clearTexture(self:Int, texture:GpuTexture):Void;
	@:hlNative("xidl", "gpu_encoder_render_set_index_buffer")
	public static function renderSetIndexBuffer(self:Int, buffer:GpuBuffer, format:IndexFormat):Void;
	@:hlNative("xidl", "gpu_encoder_render_draw_indexed")
	public static function renderDrawIndexed(self:Int, indices:Int, instances:Int):Void;
	@:hlNative("xidl", "gpu_encoder_render_set_blend_constant")
	public static function renderSetBlendConstant(self:Int, r:Float, g:Float, b:Float, a:Float):Void;
	@:hlNative("xidl", "gpu_encoder_render_set_stencil_reference")
	public static function renderSetStencilReference(self:Int, reference:Int):Void;
	@:hlNative("xidl", "gpu_encoder_compute_indirect")
	public static function computeIndirect(self:Int, pipeline:GpuPipeline, bindgroup:GpuBindGroup, buffer:GpuBuffer, offset:haxe.Int64):Void;
	@:hlNative("xidl", "gpu_encoder_render_draw_indirect")
	public static function renderDrawIndirect(self:Int, buffer:GpuBuffer, offset:haxe.Int64):Void;
	@:hlNative("xidl", "gpu_encoder_render_draw_indexed_indirect")
	public static function renderDrawIndexedIndirect(self:Int, buffer:GpuBuffer, offset:haxe.Int64):Void;
	@:hlNative("xidl", "gpu_encoder_push_debug_group")
	public static function pushDebugGroup(self:Int, label:String):Void;
	@:hlNative("xidl", "gpu_encoder_pop_debug_group")
	public static function popDebugGroup(self:Int):Void;
	@:hlNative("xidl", "gpu_encoder_insert_debug_marker")
	public static function insertDebugMarker(self:Int, label:String):Void;
}
