// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuExternalTextureBindingLayout(hl.Abstract<"xidl_GpuExternalTextureBindingLayout">) {
	public inline function new() this = GpuExternalTextureBindingLayoutNative.create();
}

private extern class GpuExternalTextureBindingLayoutNative {
	@:hlNative("xidl", "gpu_external_texture_binding_layout_new")
	public static function create():hl.Abstract<"xidl_GpuExternalTextureBindingLayout">;
}
