// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuFragmentState(hl.Abstract<"xidl_GpuFragmentState">) {
	public inline function new(module:GpuShader) this = GpuFragmentStateNative.create(module);
	public inline function entryPoint(value:String):Void GpuFragmentStateNative.entryPoint(this, value);
	public inline function addConstants(key:String, value:Float):Void GpuFragmentStateNative.addConstants(this, key, value);
	public inline function addTargets(value:GpuColorTargetState):Void GpuFragmentStateNative.addTargets(this, value);
}

private extern class GpuFragmentStateNative {
	@:hlNative("xidl", "gpu_fragment_state_new")
	public static function create(module:GpuShader):hl.Abstract<"xidl_GpuFragmentState">;
	@:hlNative("xidl", "gpu_fragment_state_entry_point")
	public static function entryPoint(self:hl.Abstract<"xidl_GpuFragmentState">, value:String):Void;
	@:hlNative("xidl", "gpu_fragment_state_add_constants")
	public static function addConstants(self:hl.Abstract<"xidl_GpuFragmentState">, key:String, value:Float):Void;
	@:hlNative("xidl", "gpu_fragment_state_add_targets")
	public static function addTargets(self:hl.Abstract<"xidl_GpuFragmentState">, value:GpuColorTargetState):Void;
}
