// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuInstance(Int) from Int to Int {
	public inline function valid():Bool return GpuInstanceNative.valid(this);
	public inline function new() this = GpuInstanceNative.create();
	public inline function destroy():Void GpuInstanceNative.destroy(this);
	public inline function requestAdapter(power:Power):ash.Future<GpuAdapter> return GpuInstanceNative.requestAdapter(this, power);
	public static inline function createWith(descriptor:GpuInstanceDescriptor):GpuInstance return GpuInstanceNative.createWith(descriptor);
	public inline function requestAdapterWith(options:GpuRequestAdapterOptions):ash.Future<GpuAdapter> return GpuInstanceNative.requestAdapterWith(this, options);
	public inline function surface(platform:Int, wa:haxe.Int64, wb:haxe.Int64, da:haxe.Int64, db:haxe.Int64):GpuSurface return GpuInstanceNative.surface(this, platform, wa, wb, da, db);
}

private extern class GpuInstanceNative {
	@:hlNative("xgpu", "gpu_instance_valid")
	public static function valid(self:Int):Bool;
	@:hlNative("xgpu", "gpu_instance_new")
	public static function create():GpuInstance;
	@:hlNative("xgpu", "gpu_instance_destroy")
	public static function destroy(self:Int):Void;
	@:hlNative("xgpu", "gpu_instance_request_adapter")
	public static function requestAdapter(self:Int, power:Power):ash.Future<GpuAdapter>;
	@:hlNative("xgpu", "gpu_instance_create_with")
	public static function createWith(descriptor:GpuInstanceDescriptor):GpuInstance;
	@:hlNative("xgpu", "gpu_instance_request_adapter_with")
	public static function requestAdapterWith(self:Int, options:GpuRequestAdapterOptions):ash.Future<GpuAdapter>;
	@:hlNative("xgpu", "gpu_instance_surface")
	public static function surface(self:Int, platform:Int, wa:haxe.Int64, wb:haxe.Int64, da:haxe.Int64, db:haxe.Int64):GpuSurface;
}
