// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuInstanceDescriptor(hl.Abstract<"xgpu_GpuInstanceDescriptor">) {
	public inline function new() this = GpuInstanceDescriptorNative.create();
	public inline function backends(value:Int):Void GpuInstanceDescriptorNative.backends(this, value);
	public inline function flags(value:Int):Void GpuInstanceDescriptorNative.flags(this, value);
}

private extern class GpuInstanceDescriptorNative {
	@:hlNative("xgpu", "gpu_instance_descriptor_new")
	public static function create():hl.Abstract<"xgpu_GpuInstanceDescriptor">;
	@:hlNative("xgpu", "gpu_instance_descriptor_backends")
	public static function backends(self:hl.Abstract<"xgpu_GpuInstanceDescriptor">, value:Int):Void;
	@:hlNative("xgpu", "gpu_instance_descriptor_flags")
	public static function flags(self:hl.Abstract<"xgpu_GpuInstanceDescriptor">, value:Int):Void;
}
