// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuMultisampleState(hl.Abstract<"xgpu_GpuMultisampleState">) {
	public inline function new() this = GpuMultisampleStateNative.create();
	public inline function count(value:Int):Void GpuMultisampleStateNative.count(this, value);
	public inline function mask(value:Int):Void GpuMultisampleStateNative.mask(this, value);
	public inline function alphaToCoverageEnabled(value:Bool):Void GpuMultisampleStateNative.alphaToCoverageEnabled(this, value);
}

private extern class GpuMultisampleStateNative {
	@:hlNative("xgpu", "gpu_multisample_state_new")
	public static function create():hl.Abstract<"xgpu_GpuMultisampleState">;
	@:hlNative("xgpu", "gpu_multisample_state_count")
	public static function count(self:hl.Abstract<"xgpu_GpuMultisampleState">, value:Int):Void;
	@:hlNative("xgpu", "gpu_multisample_state_mask")
	public static function mask(self:hl.Abstract<"xgpu_GpuMultisampleState">, value:Int):Void;
	@:hlNative("xgpu", "gpu_multisample_state_alpha_to_coverage_enabled")
	public static function alphaToCoverageEnabled(self:hl.Abstract<"xgpu_GpuMultisampleState">, value:Bool):Void;
}
