// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuMeshPipelineDescriptor(hl.Abstract<"xgpu_GpuMeshPipelineDescriptor">) {
	public inline function new(mesh:GpuProgrammableStage) this = GpuMeshPipelineDescriptorNative.create(mesh);
	public inline function label(value:String):Void GpuMeshPipelineDescriptorNative.label(this, value);
	public inline function layout(value:GpuPipelineLayout):Void GpuMeshPipelineDescriptorNative.layout(this, value);
	public inline function task(value:GpuProgrammableStage):Void GpuMeshPipelineDescriptorNative.task(this, value);
	public inline function primitive(value:GpuPrimitiveState):Void GpuMeshPipelineDescriptorNative.primitive(this, value);
	public inline function depthStencil(value:GpuDepthStencilState):Void GpuMeshPipelineDescriptorNative.depthStencil(this, value);
	public inline function multisample(value:GpuMultisampleState):Void GpuMeshPipelineDescriptorNative.multisample(this, value);
	public inline function fragment(value:GpuFragmentState):Void GpuMeshPipelineDescriptorNative.fragment(this, value);
	public inline function multiview(value:Int):Void GpuMeshPipelineDescriptorNative.multiview(this, value);
	public inline function cache(value:GpuPipelineCache):Void GpuMeshPipelineDescriptorNative.cache(this, value);
}

private extern class GpuMeshPipelineDescriptorNative {
	@:hlNative("xgpu", "gpu_mesh_pipeline_descriptor_new")
	public static function create(mesh:GpuProgrammableStage):hl.Abstract<"xgpu_GpuMeshPipelineDescriptor">;
	@:hlNative("xgpu", "gpu_mesh_pipeline_descriptor_label")
	public static function label(self:hl.Abstract<"xgpu_GpuMeshPipelineDescriptor">, value:String):Void;
	@:hlNative("xgpu", "gpu_mesh_pipeline_descriptor_layout")
	public static function layout(self:hl.Abstract<"xgpu_GpuMeshPipelineDescriptor">, value:GpuPipelineLayout):Void;
	@:hlNative("xgpu", "gpu_mesh_pipeline_descriptor_task")
	public static function task(self:hl.Abstract<"xgpu_GpuMeshPipelineDescriptor">, value:GpuProgrammableStage):Void;
	@:hlNative("xgpu", "gpu_mesh_pipeline_descriptor_primitive")
	public static function primitive(self:hl.Abstract<"xgpu_GpuMeshPipelineDescriptor">, value:GpuPrimitiveState):Void;
	@:hlNative("xgpu", "gpu_mesh_pipeline_descriptor_depth_stencil")
	public static function depthStencil(self:hl.Abstract<"xgpu_GpuMeshPipelineDescriptor">, value:GpuDepthStencilState):Void;
	@:hlNative("xgpu", "gpu_mesh_pipeline_descriptor_multisample")
	public static function multisample(self:hl.Abstract<"xgpu_GpuMeshPipelineDescriptor">, value:GpuMultisampleState):Void;
	@:hlNative("xgpu", "gpu_mesh_pipeline_descriptor_fragment")
	public static function fragment(self:hl.Abstract<"xgpu_GpuMeshPipelineDescriptor">, value:GpuFragmentState):Void;
	@:hlNative("xgpu", "gpu_mesh_pipeline_descriptor_multiview")
	public static function multiview(self:hl.Abstract<"xgpu_GpuMeshPipelineDescriptor">, value:Int):Void;
	@:hlNative("xgpu", "gpu_mesh_pipeline_descriptor_cache")
	public static function cache(self:hl.Abstract<"xgpu_GpuMeshPipelineDescriptor">, value:GpuPipelineCache):Void;
}
