// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuOrigin3D(hl.Abstract<"xgpu_GpuOrigin3D">) {
	public inline function new() this = GpuOrigin3DNative.create();
	public inline function x(value:Int):Void GpuOrigin3DNative.x(this, value);
	public inline function y(value:Int):Void GpuOrigin3DNative.y(this, value);
	public inline function z(value:Int):Void GpuOrigin3DNative.z(this, value);
}

private extern class GpuOrigin3DNative {
	@:hlNative("xgpu", "gpu_origin3_d_new")
	public static function create():hl.Abstract<"xgpu_GpuOrigin3D">;
	@:hlNative("xgpu", "gpu_origin3_d_x")
	public static function x(self:hl.Abstract<"xgpu_GpuOrigin3D">, value:Int):Void;
	@:hlNative("xgpu", "gpu_origin3_d_y")
	public static function y(self:hl.Abstract<"xgpu_GpuOrigin3D">, value:Int):Void;
	@:hlNative("xgpu", "gpu_origin3_d_z")
	public static function z(self:hl.Abstract<"xgpu_GpuOrigin3D">, value:Int):Void;
}
