// Generated by xgpu-bindgen. Do not edit by hand.
package gpu;

abstract GpuPassthroughEntryPoint(hl.Abstract<"xgpu_GpuPassthroughEntryPoint">) {
	public inline function new(name:String) this = GpuPassthroughEntryPointNative.create(name);
	public inline function workgroupX(value:Int):Void GpuPassthroughEntryPointNative.workgroupX(this, value);
	public inline function workgroupY(value:Int):Void GpuPassthroughEntryPointNative.workgroupY(this, value);
	public inline function workgroupZ(value:Int):Void GpuPassthroughEntryPointNative.workgroupZ(this, value);
}

private extern class GpuPassthroughEntryPointNative {
	@:hlNative("xgpu", "gpu_passthrough_entry_point_new")
	public static function create(name:String):hl.Abstract<"xgpu_GpuPassthroughEntryPoint">;
	@:hlNative("xgpu", "gpu_passthrough_entry_point_workgroup_x")
	public static function workgroupX(self:hl.Abstract<"xgpu_GpuPassthroughEntryPoint">, value:Int):Void;
	@:hlNative("xgpu", "gpu_passthrough_entry_point_workgroup_y")
	public static function workgroupY(self:hl.Abstract<"xgpu_GpuPassthroughEntryPoint">, value:Int):Void;
	@:hlNative("xgpu", "gpu_passthrough_entry_point_workgroup_z")
	public static function workgroupZ(self:hl.Abstract<"xgpu_GpuPassthroughEntryPoint">, value:Int):Void;
}
