// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuPipelineBuilder(Int) from Int to Int {
	public inline function destroy():Void GpuPipelineBuilderNative.destroy(this);
	public inline function valid():Bool return GpuPipelineBuilderNative.valid(this);
	public inline function shader(shader:GpuShader, vs:String, fs:String):Void GpuPipelineBuilderNative.shader(this, shader, vs, fs);
	public inline function layout(layout:GpuPipelineLayout):Void GpuPipelineBuilderNative.layout(this, layout);
	public inline function vertexBuffer(stride:haxe.Int64, step:VertexStepMode):Void GpuPipelineBuilderNative.vertexBuffer(this, stride, step);
	public inline function attributePacked(format:VertexFormat):Void GpuPipelineBuilderNative.attributePacked(this, format);
	public inline function attribute(format:VertexFormat, offset:haxe.Int64, location:Int):Void GpuPipelineBuilderNative.attribute(this, format, offset, location);
	public inline function target(format:TextureFormat, write_mask:Int):Void GpuPipelineBuilderNative.target(this, format, write_mask);
	public inline function blend(src:BlendFactor, dst:BlendFactor, op:BlendOperation, src_alpha:BlendFactor, dst_alpha:BlendFactor, op_alpha:BlendOperation):Void GpuPipelineBuilderNative.blend(this, src, dst, op, src_alpha, dst_alpha, op_alpha);
	public inline function stencil(compare:CompareFunction, fail:StencilOperation, depth_fail:StencilOperation, pass_op:StencilOperation, read_mask:Int, write_mask:Int):Void GpuPipelineBuilderNative.stencil(this, compare, fail, depth_fail, pass_op, read_mask, write_mask);
	public inline function depth(format:TextureFormat, write:Bool, compare:CompareFunction):Void GpuPipelineBuilderNative.depth(this, format, write, compare);
	public inline function primitive(topology:PrimitiveTopology, cull:CullMode, front:FrontFace):Void GpuPipelineBuilderNative.primitive(this, topology, cull, front);
	public inline function build():GpuPipeline return GpuPipelineBuilderNative.build(this);
}

private extern class GpuPipelineBuilderNative {
	@:hlNative("xidl", "gpu_pipeline_builder_destroy")
	public static function destroy(self:Int):Void;
	@:hlNative("xidl", "gpu_pipeline_builder_valid")
	public static function valid(self:Int):Bool;
	@:hlNative("xidl", "gpu_pipeline_builder_shader")
	public static function shader(self:Int, shader:GpuShader, vs:String, fs:String):Void;
	@:hlNative("xidl", "gpu_pipeline_builder_layout")
	public static function layout(self:Int, layout:GpuPipelineLayout):Void;
	@:hlNative("xidl", "gpu_pipeline_builder_vertex_buffer")
	public static function vertexBuffer(self:Int, stride:haxe.Int64, step:VertexStepMode):Void;
	@:hlNative("xidl", "gpu_pipeline_builder_attribute_packed")
	public static function attributePacked(self:Int, format:VertexFormat):Void;
	@:hlNative("xidl", "gpu_pipeline_builder_attribute")
	public static function attribute(self:Int, format:VertexFormat, offset:haxe.Int64, location:Int):Void;
	@:hlNative("xidl", "gpu_pipeline_builder_target")
	public static function target(self:Int, format:TextureFormat, write_mask:Int):Void;
	@:hlNative("xidl", "gpu_pipeline_builder_blend")
	public static function blend(self:Int, src:BlendFactor, dst:BlendFactor, op:BlendOperation, src_alpha:BlendFactor, dst_alpha:BlendFactor, op_alpha:BlendOperation):Void;
	@:hlNative("xidl", "gpu_pipeline_builder_stencil")
	public static function stencil(self:Int, compare:CompareFunction, fail:StencilOperation, depth_fail:StencilOperation, pass_op:StencilOperation, read_mask:Int, write_mask:Int):Void;
	@:hlNative("xidl", "gpu_pipeline_builder_depth")
	public static function depth(self:Int, format:TextureFormat, write:Bool, compare:CompareFunction):Void;
	@:hlNative("xidl", "gpu_pipeline_builder_primitive")
	public static function primitive(self:Int, topology:PrimitiveTopology, cull:CullMode, front:FrontFace):Void;
	@:hlNative("xidl", "gpu_pipeline_builder_build")
	public static function build(self:Int):GpuPipeline;
}
