// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuPassthroughShaderDescriptor(hl.Abstract<"xidl_GpuPassthroughShaderDescriptor">) {
	public inline function new() this = GpuPassthroughShaderDescriptorNative.create();
	public inline function label(value:String):Void GpuPassthroughShaderDescriptorNative.label(this, value);
	public inline function addEntryPoints(value:GpuPassthroughEntryPoint):Void GpuPassthroughShaderDescriptorNative.addEntryPoints(this, value);
	public inline function spirv(value:haxe.io.Bytes):Void GpuPassthroughShaderDescriptorNative.spirv(this, value);
	public inline function dxil(value:haxe.io.Bytes):Void GpuPassthroughShaderDescriptorNative.dxil(this, value);
	public inline function hlsl(value:String):Void GpuPassthroughShaderDescriptorNative.hlsl(this, value);
	public inline function metallib(value:haxe.io.Bytes):Void GpuPassthroughShaderDescriptorNative.metallib(this, value);
	public inline function msl(value:String):Void GpuPassthroughShaderDescriptorNative.msl(this, value);
	public inline function wgsl(value:String):Void GpuPassthroughShaderDescriptorNative.wgsl(this, value);
}

private extern class GpuPassthroughShaderDescriptorNative {
	@:hlNative("xidl", "gpu_passthrough_shader_descriptor_new")
	public static function create():hl.Abstract<"xidl_GpuPassthroughShaderDescriptor">;
	@:hlNative("xidl", "gpu_passthrough_shader_descriptor_label")
	public static function label(self:hl.Abstract<"xidl_GpuPassthroughShaderDescriptor">, value:String):Void;
	@:hlNative("xidl", "gpu_passthrough_shader_descriptor_add_entry_points")
	public static function addEntryPoints(self:hl.Abstract<"xidl_GpuPassthroughShaderDescriptor">, value:GpuPassthroughEntryPoint):Void;
	@:hlNative("xidl", "gpu_passthrough_shader_descriptor_spirv")
	public static function spirv(self:hl.Abstract<"xidl_GpuPassthroughShaderDescriptor">, value:haxe.io.Bytes):Void;
	@:hlNative("xidl", "gpu_passthrough_shader_descriptor_dxil")
	public static function dxil(self:hl.Abstract<"xidl_GpuPassthroughShaderDescriptor">, value:haxe.io.Bytes):Void;
	@:hlNative("xidl", "gpu_passthrough_shader_descriptor_hlsl")
	public static function hlsl(self:hl.Abstract<"xidl_GpuPassthroughShaderDescriptor">, value:String):Void;
	@:hlNative("xidl", "gpu_passthrough_shader_descriptor_metallib")
	public static function metallib(self:hl.Abstract<"xidl_GpuPassthroughShaderDescriptor">, value:haxe.io.Bytes):Void;
	@:hlNative("xidl", "gpu_passthrough_shader_descriptor_msl")
	public static function msl(self:hl.Abstract<"xidl_GpuPassthroughShaderDescriptor">, value:String):Void;
	@:hlNative("xidl", "gpu_passthrough_shader_descriptor_wgsl")
	public static function wgsl(self:hl.Abstract<"xidl_GpuPassthroughShaderDescriptor">, value:String):Void;
}
