// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuPipelineLayoutDescriptor(hl.Abstract<"xidl_GpuPipelineLayoutDescriptor">) {
	public inline function new() this = GpuPipelineLayoutDescriptorNative.create();
	public inline function label(value:String):Void GpuPipelineLayoutDescriptorNative.label(this, value);
	public inline function addBindGroupLayouts(value:GpuBindGroupLayout):Void GpuPipelineLayoutDescriptorNative.addBindGroupLayouts(this, value);
	public inline function immediateSize(value:Int):Void GpuPipelineLayoutDescriptorNative.immediateSize(this, value);
}

private extern class GpuPipelineLayoutDescriptorNative {
	@:hlNative("xidl", "gpu_pipeline_layout_descriptor_new")
	public static function create():hl.Abstract<"xidl_GpuPipelineLayoutDescriptor">;
	@:hlNative("xidl", "gpu_pipeline_layout_descriptor_label")
	public static function label(self:hl.Abstract<"xidl_GpuPipelineLayoutDescriptor">, value:String):Void;
	@:hlNative("xidl", "gpu_pipeline_layout_descriptor_add_bind_group_layouts")
	public static function addBindGroupLayouts(self:hl.Abstract<"xidl_GpuPipelineLayoutDescriptor">, value:GpuBindGroupLayout):Void;
	@:hlNative("xidl", "gpu_pipeline_layout_descriptor_immediate_size")
	public static function immediateSize(self:hl.Abstract<"xidl_GpuPipelineLayoutDescriptor">, value:Int):Void;
}
