// Generated by xgpu-bindgen. Do not edit by hand.
package gpu;

abstract GpuPipelineCacheDescriptor(hl.Abstract<"xgpu_GpuPipelineCacheDescriptor">) {
	public inline function new() this = GpuPipelineCacheDescriptorNative.create();
	public inline function label(value:String):Void GpuPipelineCacheDescriptorNative.label(this, value);
	public inline function data(value:haxe.io.Bytes):Void GpuPipelineCacheDescriptorNative.data(this, value);
	public inline function fallback(value:Bool):Void GpuPipelineCacheDescriptorNative.fallback(this, value);
}

private extern class GpuPipelineCacheDescriptorNative {
	@:hlNative("xgpu", "gpu_pipeline_cache_descriptor_new")
	public static function create():hl.Abstract<"xgpu_GpuPipelineCacheDescriptor">;
	@:hlNative("xgpu", "gpu_pipeline_cache_descriptor_label")
	public static function label(self:hl.Abstract<"xgpu_GpuPipelineCacheDescriptor">, value:String):Void;
	@:hlNative("xgpu", "gpu_pipeline_cache_descriptor_data")
	public static function data(self:hl.Abstract<"xgpu_GpuPipelineCacheDescriptor">, value:haxe.io.Bytes):Void;
	@:hlNative("xgpu", "gpu_pipeline_cache_descriptor_fallback")
	public static function fallback(self:hl.Abstract<"xgpu_GpuPipelineCacheDescriptor">, value:Bool):Void;
}
