// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuPipeline(Int) from Int to Int {
	public inline function valid():Bool return GpuPipelineNative.valid(this);
	public inline function destroy():Void GpuPipelineNative.destroy(this);
	public inline function getBindGroupLayout(index:Int):GpuBindGroupLayout return GpuPipelineNative.getBindGroupLayout(this, index);
}

private extern class GpuPipelineNative {
	@:hlNative("xgpu", "gpu_pipeline_valid")
	public static function valid(self:Int):Bool;
	@:hlNative("xgpu", "gpu_pipeline_destroy")
	public static function destroy(self:Int):Void;
	@:hlNative("xgpu", "gpu_pipeline_get_bind_group_layout")
	public static function getBindGroupLayout(self:Int, index:Int):GpuBindGroupLayout;
}
