// Generated by xgpu-bindgen. Do not edit by hand.
package gpu;

abstract GpuProgrammableStage(hl.Abstract<"xgpu_GpuProgrammableStage">) {
	public inline function new(module:GpuShader) this = GpuProgrammableStageNative.create(module);
	public inline function entryPoint(value:String):Void GpuProgrammableStageNative.entryPoint(this, value);
	public inline function addConstants(key:String, value:Float):Void GpuProgrammableStageNative.addConstants(this, key, value);
}

private extern class GpuProgrammableStageNative {
	@:hlNative("xgpu", "gpu_programmable_stage_new")
	public static function create(module:GpuShader):hl.Abstract<"xgpu_GpuProgrammableStage">;
	@:hlNative("xgpu", "gpu_programmable_stage_entry_point")
	public static function entryPoint(self:hl.Abstract<"xgpu_GpuProgrammableStage">, value:String):Void;
	@:hlNative("xgpu", "gpu_programmable_stage_add_constants")
	public static function addConstants(self:hl.Abstract<"xgpu_GpuProgrammableStage">, key:String, value:Float):Void;
}
