// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuPipelineLayout(Int) from Int to Int {
	public inline function valid():Bool return GpuPipelineLayoutNative.valid(this);
	public inline function destroy():Void GpuPipelineLayoutNative.destroy(this);
}

private extern class GpuPipelineLayoutNative {
	@:hlNative("xidl", "gpu_pipeline_layout_valid")
	public static function valid(self:Int):Bool;
	@:hlNative("xidl", "gpu_pipeline_layout_destroy")
	public static function destroy(self:Int):Void;
}
