// Generated by xgpu-bindgen. Do not edit by hand.
package gpu;

abstract GpuPrimitiveState(hl.Abstract<"xgpu_GpuPrimitiveState">) {
	public inline function new() this = GpuPrimitiveStateNative.create();
	public inline function topology(value:PrimitiveTopology):Void GpuPrimitiveStateNative.topology(this, value);
	public inline function stripIndexFormat(value:IndexFormat):Void GpuPrimitiveStateNative.stripIndexFormat(this, value);
	public inline function frontFace(value:FrontFace):Void GpuPrimitiveStateNative.frontFace(this, value);
	public inline function cullMode(value:CullMode):Void GpuPrimitiveStateNative.cullMode(this, value);
	public inline function unclippedDepth(value:Bool):Void GpuPrimitiveStateNative.unclippedDepth(this, value);
	public inline function polygonMode(value:PolygonMode):Void GpuPrimitiveStateNative.polygonMode(this, value);
	public inline function conservative(value:Bool):Void GpuPrimitiveStateNative.conservative(this, value);
}

private extern class GpuPrimitiveStateNative {
	@:hlNative("xgpu", "gpu_primitive_state_new")
	public static function create():hl.Abstract<"xgpu_GpuPrimitiveState">;
	@:hlNative("xgpu", "gpu_primitive_state_topology")
	public static function topology(self:hl.Abstract<"xgpu_GpuPrimitiveState">, value:PrimitiveTopology):Void;
	@:hlNative("xgpu", "gpu_primitive_state_strip_index_format")
	public static function stripIndexFormat(self:hl.Abstract<"xgpu_GpuPrimitiveState">, value:IndexFormat):Void;
	@:hlNative("xgpu", "gpu_primitive_state_front_face")
	public static function frontFace(self:hl.Abstract<"xgpu_GpuPrimitiveState">, value:FrontFace):Void;
	@:hlNative("xgpu", "gpu_primitive_state_cull_mode")
	public static function cullMode(self:hl.Abstract<"xgpu_GpuPrimitiveState">, value:CullMode):Void;
	@:hlNative("xgpu", "gpu_primitive_state_unclipped_depth")
	public static function unclippedDepth(self:hl.Abstract<"xgpu_GpuPrimitiveState">, value:Bool):Void;
	@:hlNative("xgpu", "gpu_primitive_state_polygon_mode")
	public static function polygonMode(self:hl.Abstract<"xgpu_GpuPrimitiveState">, value:PolygonMode):Void;
	@:hlNative("xgpu", "gpu_primitive_state_conservative")
	public static function conservative(self:hl.Abstract<"xgpu_GpuPrimitiveState">, value:Bool):Void;
}
