// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuPipelineCache(Int) from Int to Int {
	public inline function valid():Bool return GpuPipelineCacheNative.valid(this);
	public inline function destroy():Void GpuPipelineCacheNative.destroy(this);
	public inline function getData():haxe.io.Bytes return XidlBytes.take(GpuPipelineCacheNative.getData(this));
}

private extern class GpuPipelineCacheNative {
	@:hlNative("xidl", "gpu_pipeline_cache_valid")
	public static function valid(self:Int):Bool;
	@:hlNative("xidl", "gpu_pipeline_cache_destroy")
	public static function destroy(self:Int):Void;
	@:hlNative("xidl", "gpu_pipeline_cache_get_data")
	public static function getData(self:Int):hl.Abstract<"xidl_buffer_result">;
}
