// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuQueue(Int) from Int to Int {
	public inline function valid():Bool return GpuQueueNative.valid(this);
	public inline function writeBuffer(buffer:GpuBuffer, offset:haxe.Int64, data:haxe.io.Bytes, len:Int):Void GpuQueueNative.writeBuffer(this, buffer, offset, data, len);
	public inline function writeTexture(texture:GpuTexture, data:haxe.io.Bytes, width:Int, height:Int, bytes_per_row:Int):Void GpuQueueNative.writeTexture(this, texture, data, width, height, bytes_per_row);
	public inline function presentSurface(surface:GpuSurface):Void GpuQueueNative.presentSurface(this, surface);
	public inline function writeTextureWith(destination:GpuTexelCopyTextureInfo, data:haxe.io.Bytes, layout:GpuTexelCopyBufferLayout, size:GpuExtent3D):Void GpuQueueNative.writeTextureWith(this, destination, data, layout, size);
	public inline function timestampPeriod():Float return GpuQueueNative.timestampPeriod(this);
	public inline function compactBlas(blas:GpuBlas):GpuBlas return GpuQueueNative.compactBlas(this, blas);
}

private extern class GpuQueueNative {
	@:hlNative("xgpu", "gpu_queue_valid")
	public static function valid(self:Int):Bool;
	@:hlNative("xgpu", "gpu_queue_write_buffer")
	public static function writeBuffer(self:Int, buffer:GpuBuffer, offset:haxe.Int64, data:haxe.io.Bytes, len:Int):Void;
	@:hlNative("xgpu", "gpu_queue_write_texture")
	public static function writeTexture(self:Int, texture:GpuTexture, data:haxe.io.Bytes, width:Int, height:Int, bytes_per_row:Int):Void;
	@:hlNative("xgpu", "gpu_queue_present_surface")
	public static function presentSurface(self:Int, surface:GpuSurface):Void;
	@:hlNative("xgpu", "gpu_queue_write_texture_with")
	public static function writeTextureWith(self:Int, destination:GpuTexelCopyTextureInfo, data:haxe.io.Bytes, layout:GpuTexelCopyBufferLayout, size:GpuExtent3D):Void;
	@:hlNative("xgpu", "gpu_queue_timestamp_period")
	public static function timestampPeriod(self:Int):Float;
	@:hlNative("xgpu", "gpu_queue_compact_blas")
	public static function compactBlas(self:Int, blas:GpuBlas):GpuBlas;
}
