// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuQuerySet(Int) from Int to Int {
	public inline function valid():Bool return GpuQuerySetNative.valid(this);
	public inline function destroy():Void GpuQuerySetNative.destroy(this);
	public inline function count():Int return GpuQuerySetNative.count(this);
	public inline function queryType():QueryType return GpuQuerySetNative.queryType(this);
}

private extern class GpuQuerySetNative {
	@:hlNative("xidl", "gpu_query_set_valid")
	public static function valid(self:Int):Bool;
	@:hlNative("xidl", "gpu_query_set_destroy")
	public static function destroy(self:Int):Void;
	@:hlNative("xidl", "gpu_query_set_count")
	public static function count(self:Int):Int;
	@:hlNative("xidl", "gpu_query_set_query_type")
	public static function queryType(self:Int):QueryType;
}
