// Generated by xgpu-bindgen. Do not edit by hand.
package gpu;

abstract GpuQuerySetDescriptor(hl.Abstract<"xgpu_GpuQuerySetDescriptor">) {
	public inline function new(type:QueryType, count:Int) this = GpuQuerySetDescriptorNative.create(type, count);
	public inline function label(value:String):Void GpuQuerySetDescriptorNative.label(this, value);
	public inline function pipelineStatistics(value:Int):Void GpuQuerySetDescriptorNative.pipelineStatistics(this, value);
}

private extern class GpuQuerySetDescriptorNative {
	@:hlNative("xgpu", "gpu_query_set_descriptor_new")
	public static function create(type:QueryType, count:Int):hl.Abstract<"xgpu_GpuQuerySetDescriptor">;
	@:hlNative("xgpu", "gpu_query_set_descriptor_label")
	public static function label(self:hl.Abstract<"xgpu_GpuQuerySetDescriptor">, value:String):Void;
	@:hlNative("xgpu", "gpu_query_set_descriptor_pipeline_statistics")
	public static function pipelineStatistics(self:hl.Abstract<"xgpu_GpuQuerySetDescriptor">, value:Int):Void;
}
