// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuRenderBundle(Int) from Int to Int {
	public inline function valid():Bool return GpuRenderBundleNative.valid(this);
	public inline function destroy():Void GpuRenderBundleNative.destroy(this);
}

private extern class GpuRenderBundleNative {
	@:hlNative("xidl", "gpu_render_bundle_valid")
	public static function valid(self:Int):Bool;
	@:hlNative("xidl", "gpu_render_bundle_destroy")
	public static function destroy(self:Int):Void;
}
