// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuRenderPassTimestampWrites(hl.Abstract<"xgpu_GpuRenderPassTimestampWrites">) {
	public inline function new(querySet:GpuQuerySet) this = GpuRenderPassTimestampWritesNative.create(querySet);
	public inline function beginningOfPassWriteIndex(value:Int):Void GpuRenderPassTimestampWritesNative.beginningOfPassWriteIndex(this, value);
	public inline function endOfPassWriteIndex(value:Int):Void GpuRenderPassTimestampWritesNative.endOfPassWriteIndex(this, value);
}

private extern class GpuRenderPassTimestampWritesNative {
	@:hlNative("xgpu", "gpu_render_pass_timestamp_writes_new")
	public static function create(querySet:GpuQuerySet):hl.Abstract<"xgpu_GpuRenderPassTimestampWrites">;
	@:hlNative("xgpu", "gpu_render_pass_timestamp_writes_beginning_of_pass_write_index")
	public static function beginningOfPassWriteIndex(self:hl.Abstract<"xgpu_GpuRenderPassTimestampWrites">, value:Int):Void;
	@:hlNative("xgpu", "gpu_render_pass_timestamp_writes_end_of_pass_write_index")
	public static function endOfPassWriteIndex(self:hl.Abstract<"xgpu_GpuRenderPassTimestampWrites">, value:Int):Void;
}
