// Generated by xgpu-bindgen. Do not edit by hand.
package gpu;

abstract GpuRequestAdapterOptions(hl.Abstract<"xgpu_GpuRequestAdapterOptions">) {
	public inline function new() this = GpuRequestAdapterOptionsNative.create();
	public inline function powerPreference(value:Power):Void GpuRequestAdapterOptionsNative.powerPreference(this, value);
	public inline function forceFallbackAdapter(value:Bool):Void GpuRequestAdapterOptionsNative.forceFallbackAdapter(this, value);
	public inline function compatibleSurface(value:GpuSurface):Void GpuRequestAdapterOptionsNative.compatibleSurface(this, value);
}

private extern class GpuRequestAdapterOptionsNative {
	@:hlNative("xgpu", "gpu_request_adapter_options_new")
	public static function create():hl.Abstract<"xgpu_GpuRequestAdapterOptions">;
	@:hlNative("xgpu", "gpu_request_adapter_options_power_preference")
	public static function powerPreference(self:hl.Abstract<"xgpu_GpuRequestAdapterOptions">, value:Power):Void;
	@:hlNative("xgpu", "gpu_request_adapter_options_force_fallback_adapter")
	public static function forceFallbackAdapter(self:hl.Abstract<"xgpu_GpuRequestAdapterOptions">, value:Bool):Void;
	@:hlNative("xgpu", "gpu_request_adapter_options_compatible_surface")
	public static function compatibleSurface(self:hl.Abstract<"xgpu_GpuRequestAdapterOptions">, value:GpuSurface):Void;
}
