// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuRenderBundleEncoder(Int) from Int to Int {
	public inline function valid():Bool return GpuRenderBundleEncoderNative.valid(this);
	public inline function destroy():Void GpuRenderBundleEncoderNative.destroy(this);
	public inline function setPipeline(pipeline:GpuPipeline):Void GpuRenderBundleEncoderNative.setPipeline(this, pipeline);
	public inline function setBindGroup(group:Int, bindgroup:GpuBindGroup):Void GpuRenderBundleEncoderNative.setBindGroup(this, group, bindgroup);
	public inline function setBindGroupOffsets(group:Int, bindgroup:GpuBindGroup, offsets:haxe.io.Bytes, start:haxe.Int64, count:Int):Void GpuRenderBundleEncoderNative.setBindGroupOffsets(this, group, bindgroup, offsets, start, count);
	public inline function setVertexBuffer(slot:Int, buffer:GpuBuffer, offset:haxe.Int64, size:haxe.Int64):Void GpuRenderBundleEncoderNative.setVertexBuffer(this, slot, buffer, offset, size);
	public inline function setIndexBuffer(buffer:GpuBuffer, format:IndexFormat, offset:haxe.Int64, size:haxe.Int64):Void GpuRenderBundleEncoderNative.setIndexBuffer(this, buffer, format, offset, size);
	public inline function draw(vertex_count:Int, instance_count:Int, first_vertex:Int, first_instance:Int):Void GpuRenderBundleEncoderNative.draw(this, vertex_count, instance_count, first_vertex, first_instance);
	public inline function drawIndexed(index_count:Int, instance_count:Int, first_index:Int, base_vertex:Int, first_instance:Int):Void GpuRenderBundleEncoderNative.drawIndexed(this, index_count, instance_count, first_index, base_vertex, first_instance);
	public inline function drawIndirect(buffer:GpuBuffer, offset:haxe.Int64):Void GpuRenderBundleEncoderNative.drawIndirect(this, buffer, offset);
	public inline function drawIndexedIndirect(buffer:GpuBuffer, offset:haxe.Int64):Void GpuRenderBundleEncoderNative.drawIndexedIndirect(this, buffer, offset);
	public inline function finish():GpuRenderBundle return GpuRenderBundleEncoderNative.finish(this);
}

private extern class GpuRenderBundleEncoderNative {
	@:hlNative("xidl", "gpu_render_bundle_encoder_valid")
	public static function valid(self:Int):Bool;
	@:hlNative("xidl", "gpu_render_bundle_encoder_destroy")
	public static function destroy(self:Int):Void;
	@:hlNative("xidl", "gpu_render_bundle_encoder_set_pipeline")
	public static function setPipeline(self:Int, pipeline:GpuPipeline):Void;
	@:hlNative("xidl", "gpu_render_bundle_encoder_set_bind_group")
	public static function setBindGroup(self:Int, group:Int, bindgroup:GpuBindGroup):Void;
	@:hlNative("xidl", "gpu_render_bundle_encoder_set_bind_group_offsets")
	public static function setBindGroupOffsets(self:Int, group:Int, bindgroup:GpuBindGroup, offsets:haxe.io.Bytes, start:haxe.Int64, count:Int):Void;
	@:hlNative("xidl", "gpu_render_bundle_encoder_set_vertex_buffer")
	public static function setVertexBuffer(self:Int, slot:Int, buffer:GpuBuffer, offset:haxe.Int64, size:haxe.Int64):Void;
	@:hlNative("xidl", "gpu_render_bundle_encoder_set_index_buffer")
	public static function setIndexBuffer(self:Int, buffer:GpuBuffer, format:IndexFormat, offset:haxe.Int64, size:haxe.Int64):Void;
	@:hlNative("xidl", "gpu_render_bundle_encoder_draw")
	public static function draw(self:Int, vertex_count:Int, instance_count:Int, first_vertex:Int, first_instance:Int):Void;
	@:hlNative("xidl", "gpu_render_bundle_encoder_draw_indexed")
	public static function drawIndexed(self:Int, index_count:Int, instance_count:Int, first_index:Int, base_vertex:Int, first_instance:Int):Void;
	@:hlNative("xidl", "gpu_render_bundle_encoder_draw_indirect")
	public static function drawIndirect(self:Int, buffer:GpuBuffer, offset:haxe.Int64):Void;
	@:hlNative("xidl", "gpu_render_bundle_encoder_draw_indexed_indirect")
	public static function drawIndexedIndirect(self:Int, buffer:GpuBuffer, offset:haxe.Int64):Void;
	@:hlNative("xidl", "gpu_render_bundle_encoder_finish")
	public static function finish(self:Int):GpuRenderBundle;
}
