// Generated by xgpu-bindgen. Do not edit by hand.
package gpu;

abstract GpuRenderPipelineDescriptor(hl.Abstract<"xgpu_GpuRenderPipelineDescriptor">) {
	public inline function new(vertex:GpuVertexState) this = GpuRenderPipelineDescriptorNative.create(vertex);
	public inline function label(value:String):Void GpuRenderPipelineDescriptorNative.label(this, value);
	public inline function layout(value:GpuPipelineLayout):Void GpuRenderPipelineDescriptorNative.layout(this, value);
	public inline function primitive(value:GpuPrimitiveState):Void GpuRenderPipelineDescriptorNative.primitive(this, value);
	public inline function depthStencil(value:GpuDepthStencilState):Void GpuRenderPipelineDescriptorNative.depthStencil(this, value);
	public inline function multisample(value:GpuMultisampleState):Void GpuRenderPipelineDescriptorNative.multisample(this, value);
	public inline function fragment(value:GpuFragmentState):Void GpuRenderPipelineDescriptorNative.fragment(this, value);
	public inline function multiviewMask(value:Int):Void GpuRenderPipelineDescriptorNative.multiviewMask(this, value);
	public inline function cache(value:GpuPipelineCache):Void GpuRenderPipelineDescriptorNative.cache(this, value);
}

private extern class GpuRenderPipelineDescriptorNative {
	@:hlNative("xgpu", "gpu_render_pipeline_descriptor_new")
	public static function create(vertex:GpuVertexState):hl.Abstract<"xgpu_GpuRenderPipelineDescriptor">;
	@:hlNative("xgpu", "gpu_render_pipeline_descriptor_label")
	public static function label(self:hl.Abstract<"xgpu_GpuRenderPipelineDescriptor">, value:String):Void;
	@:hlNative("xgpu", "gpu_render_pipeline_descriptor_layout")
	public static function layout(self:hl.Abstract<"xgpu_GpuRenderPipelineDescriptor">, value:GpuPipelineLayout):Void;
	@:hlNative("xgpu", "gpu_render_pipeline_descriptor_primitive")
	public static function primitive(self:hl.Abstract<"xgpu_GpuRenderPipelineDescriptor">, value:GpuPrimitiveState):Void;
	@:hlNative("xgpu", "gpu_render_pipeline_descriptor_depth_stencil")
	public static function depthStencil(self:hl.Abstract<"xgpu_GpuRenderPipelineDescriptor">, value:GpuDepthStencilState):Void;
	@:hlNative("xgpu", "gpu_render_pipeline_descriptor_multisample")
	public static function multisample(self:hl.Abstract<"xgpu_GpuRenderPipelineDescriptor">, value:GpuMultisampleState):Void;
	@:hlNative("xgpu", "gpu_render_pipeline_descriptor_fragment")
	public static function fragment(self:hl.Abstract<"xgpu_GpuRenderPipelineDescriptor">, value:GpuFragmentState):Void;
	@:hlNative("xgpu", "gpu_render_pipeline_descriptor_multiview_mask")
	public static function multiviewMask(self:hl.Abstract<"xgpu_GpuRenderPipelineDescriptor">, value:Int):Void;
	@:hlNative("xgpu", "gpu_render_pipeline_descriptor_cache")
	public static function cache(self:hl.Abstract<"xgpu_GpuRenderPipelineDescriptor">, value:GpuPipelineCache):Void;
}
