// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuRenderPassDescriptor(hl.Abstract<"xidl_GpuRenderPassDescriptor">) {
	public inline function new() this = GpuRenderPassDescriptorNative.create();
	public inline function label(value:String):Void GpuRenderPassDescriptorNative.label(this, value);
	public inline function addColorAttachments(value:GpuRenderPassColorAttachment):Void GpuRenderPassDescriptorNative.addColorAttachments(this, value);
	public inline function depthStencilAttachment(value:GpuRenderPassDepthStencilAttachment):Void GpuRenderPassDescriptorNative.depthStencilAttachment(this, value);
	public inline function occlusionQuerySet(value:GpuQuerySet):Void GpuRenderPassDescriptorNative.occlusionQuerySet(this, value);
	public inline function timestampWrites(value:GpuRenderPassTimestampWrites):Void GpuRenderPassDescriptorNative.timestampWrites(this, value);
	public inline function maxDrawCount(value:haxe.Int64):Void GpuRenderPassDescriptorNative.maxDrawCount(this, value);
}

private extern class GpuRenderPassDescriptorNative {
	@:hlNative("xidl", "gpu_render_pass_descriptor_new")
	public static function create():hl.Abstract<"xidl_GpuRenderPassDescriptor">;
	@:hlNative("xidl", "gpu_render_pass_descriptor_label")
	public static function label(self:hl.Abstract<"xidl_GpuRenderPassDescriptor">, value:String):Void;
	@:hlNative("xidl", "gpu_render_pass_descriptor_add_color_attachments")
	public static function addColorAttachments(self:hl.Abstract<"xidl_GpuRenderPassDescriptor">, value:GpuRenderPassColorAttachment):Void;
	@:hlNative("xidl", "gpu_render_pass_descriptor_depth_stencil_attachment")
	public static function depthStencilAttachment(self:hl.Abstract<"xidl_GpuRenderPassDescriptor">, value:GpuRenderPassDepthStencilAttachment):Void;
	@:hlNative("xidl", "gpu_render_pass_descriptor_occlusion_query_set")
	public static function occlusionQuerySet(self:hl.Abstract<"xidl_GpuRenderPassDescriptor">, value:GpuQuerySet):Void;
	@:hlNative("xidl", "gpu_render_pass_descriptor_timestamp_writes")
	public static function timestampWrites(self:hl.Abstract<"xidl_GpuRenderPassDescriptor">, value:GpuRenderPassTimestampWrites):Void;
	@:hlNative("xidl", "gpu_render_pass_descriptor_max_draw_count")
	public static function maxDrawCount(self:hl.Abstract<"xidl_GpuRenderPassDescriptor">, value:haxe.Int64):Void;
}
