// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuRenderBundleEncoderDescriptor(hl.Abstract<"xidl_GpuRenderBundleEncoderDescriptor">) {
	public inline function new() this = GpuRenderBundleEncoderDescriptorNative.create();
	public inline function label(value:String):Void GpuRenderBundleEncoderDescriptorNative.label(this, value);
	public inline function addColorFormats(value:TextureFormat):Void GpuRenderBundleEncoderDescriptorNative.addColorFormats(this, value);
	public inline function depthStencilFormat(value:TextureFormat):Void GpuRenderBundleEncoderDescriptorNative.depthStencilFormat(this, value);
	public inline function sampleCount(value:Int):Void GpuRenderBundleEncoderDescriptorNative.sampleCount(this, value);
	public inline function depthReadOnly(value:Bool):Void GpuRenderBundleEncoderDescriptorNative.depthReadOnly(this, value);
	public inline function stencilReadOnly(value:Bool):Void GpuRenderBundleEncoderDescriptorNative.stencilReadOnly(this, value);
}

private extern class GpuRenderBundleEncoderDescriptorNative {
	@:hlNative("xidl", "gpu_render_bundle_encoder_descriptor_new")
	public static function create():hl.Abstract<"xidl_GpuRenderBundleEncoderDescriptor">;
	@:hlNative("xidl", "gpu_render_bundle_encoder_descriptor_label")
	public static function label(self:hl.Abstract<"xidl_GpuRenderBundleEncoderDescriptor">, value:String):Void;
	@:hlNative("xidl", "gpu_render_bundle_encoder_descriptor_add_color_formats")
	public static function addColorFormats(self:hl.Abstract<"xidl_GpuRenderBundleEncoderDescriptor">, value:TextureFormat):Void;
	@:hlNative("xidl", "gpu_render_bundle_encoder_descriptor_depth_stencil_format")
	public static function depthStencilFormat(self:hl.Abstract<"xidl_GpuRenderBundleEncoderDescriptor">, value:TextureFormat):Void;
	@:hlNative("xidl", "gpu_render_bundle_encoder_descriptor_sample_count")
	public static function sampleCount(self:hl.Abstract<"xidl_GpuRenderBundleEncoderDescriptor">, value:Int):Void;
	@:hlNative("xidl", "gpu_render_bundle_encoder_descriptor_depth_read_only")
	public static function depthReadOnly(self:hl.Abstract<"xidl_GpuRenderBundleEncoderDescriptor">, value:Bool):Void;
	@:hlNative("xidl", "gpu_render_bundle_encoder_descriptor_stencil_read_only")
	public static function stencilReadOnly(self:hl.Abstract<"xidl_GpuRenderBundleEncoderDescriptor">, value:Bool):Void;
}
