// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuRenderPassColorAttachment(hl.Abstract<"xidl_GpuRenderPassColorAttachment">) {
	public inline function new(loadOp:LoadOp, storeOp:StoreOp) this = GpuRenderPassColorAttachmentNative.create(loadOp, storeOp);
	public inline function viewTexture(value:GpuTexture):Void GpuRenderPassColorAttachmentNative.viewTexture(this, value);
	public inline function viewTextureView(value:GpuTextureView):Void GpuRenderPassColorAttachmentNative.viewTextureView(this, value);
	public inline function depthSlice(value:Int):Void GpuRenderPassColorAttachmentNative.depthSlice(this, value);
	public inline function resolveTargetTexture(value:GpuTexture):Void GpuRenderPassColorAttachmentNative.resolveTargetTexture(this, value);
	public inline function resolveTargetTextureView(value:GpuTextureView):Void GpuRenderPassColorAttachmentNative.resolveTargetTextureView(this, value);
	public inline function clearValue(value:GpuColor):Void GpuRenderPassColorAttachmentNative.clearValue(this, value);
}

private extern class GpuRenderPassColorAttachmentNative {
	@:hlNative("xidl", "gpu_render_pass_color_attachment_new")
	public static function create(loadOp:LoadOp, storeOp:StoreOp):hl.Abstract<"xidl_GpuRenderPassColorAttachment">;
	@:hlNative("xidl", "gpu_render_pass_color_attachment_view_texture")
	public static function viewTexture(self:hl.Abstract<"xidl_GpuRenderPassColorAttachment">, value:GpuTexture):Void;
	@:hlNative("xidl", "gpu_render_pass_color_attachment_view_texture_view")
	public static function viewTextureView(self:hl.Abstract<"xidl_GpuRenderPassColorAttachment">, value:GpuTextureView):Void;
	@:hlNative("xidl", "gpu_render_pass_color_attachment_depth_slice")
	public static function depthSlice(self:hl.Abstract<"xidl_GpuRenderPassColorAttachment">, value:Int):Void;
	@:hlNative("xidl", "gpu_render_pass_color_attachment_resolve_target_texture")
	public static function resolveTargetTexture(self:hl.Abstract<"xidl_GpuRenderPassColorAttachment">, value:GpuTexture):Void;
	@:hlNative("xidl", "gpu_render_pass_color_attachment_resolve_target_texture_view")
	public static function resolveTargetTextureView(self:hl.Abstract<"xidl_GpuRenderPassColorAttachment">, value:GpuTextureView):Void;
	@:hlNative("xidl", "gpu_render_pass_color_attachment_clear_value")
	public static function clearValue(self:hl.Abstract<"xidl_GpuRenderPassColorAttachment">, value:GpuColor):Void;
}
