// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuRenderPassDepthStencilAttachment(hl.Abstract<"xidl_GpuRenderPassDepthStencilAttachment">) {
	public inline function new() this = GpuRenderPassDepthStencilAttachmentNative.create();
	public inline function viewTexture(value:GpuTexture):Void GpuRenderPassDepthStencilAttachmentNative.viewTexture(this, value);
	public inline function viewTextureView(value:GpuTextureView):Void GpuRenderPassDepthStencilAttachmentNative.viewTextureView(this, value);
	public inline function depthClearValue(value:Float):Void GpuRenderPassDepthStencilAttachmentNative.depthClearValue(this, value);
	public inline function depthLoadOp(value:LoadOp):Void GpuRenderPassDepthStencilAttachmentNative.depthLoadOp(this, value);
	public inline function depthStoreOp(value:StoreOp):Void GpuRenderPassDepthStencilAttachmentNative.depthStoreOp(this, value);
	public inline function depthReadOnly(value:Bool):Void GpuRenderPassDepthStencilAttachmentNative.depthReadOnly(this, value);
	public inline function stencilClearValue(value:Int):Void GpuRenderPassDepthStencilAttachmentNative.stencilClearValue(this, value);
	public inline function stencilLoadOp(value:LoadOp):Void GpuRenderPassDepthStencilAttachmentNative.stencilLoadOp(this, value);
	public inline function stencilStoreOp(value:StoreOp):Void GpuRenderPassDepthStencilAttachmentNative.stencilStoreOp(this, value);
	public inline function stencilReadOnly(value:Bool):Void GpuRenderPassDepthStencilAttachmentNative.stencilReadOnly(this, value);
}

private extern class GpuRenderPassDepthStencilAttachmentNative {
	@:hlNative("xidl", "gpu_render_pass_depth_stencil_attachment_new")
	public static function create():hl.Abstract<"xidl_GpuRenderPassDepthStencilAttachment">;
	@:hlNative("xidl", "gpu_render_pass_depth_stencil_attachment_view_texture")
	public static function viewTexture(self:hl.Abstract<"xidl_GpuRenderPassDepthStencilAttachment">, value:GpuTexture):Void;
	@:hlNative("xidl", "gpu_render_pass_depth_stencil_attachment_view_texture_view")
	public static function viewTextureView(self:hl.Abstract<"xidl_GpuRenderPassDepthStencilAttachment">, value:GpuTextureView):Void;
	@:hlNative("xidl", "gpu_render_pass_depth_stencil_attachment_depth_clear_value")
	public static function depthClearValue(self:hl.Abstract<"xidl_GpuRenderPassDepthStencilAttachment">, value:Float):Void;
	@:hlNative("xidl", "gpu_render_pass_depth_stencil_attachment_depth_load_op")
	public static function depthLoadOp(self:hl.Abstract<"xidl_GpuRenderPassDepthStencilAttachment">, value:LoadOp):Void;
	@:hlNative("xidl", "gpu_render_pass_depth_stencil_attachment_depth_store_op")
	public static function depthStoreOp(self:hl.Abstract<"xidl_GpuRenderPassDepthStencilAttachment">, value:StoreOp):Void;
	@:hlNative("xidl", "gpu_render_pass_depth_stencil_attachment_depth_read_only")
	public static function depthReadOnly(self:hl.Abstract<"xidl_GpuRenderPassDepthStencilAttachment">, value:Bool):Void;
	@:hlNative("xidl", "gpu_render_pass_depth_stencil_attachment_stencil_clear_value")
	public static function stencilClearValue(self:hl.Abstract<"xidl_GpuRenderPassDepthStencilAttachment">, value:Int):Void;
	@:hlNative("xidl", "gpu_render_pass_depth_stencil_attachment_stencil_load_op")
	public static function stencilLoadOp(self:hl.Abstract<"xidl_GpuRenderPassDepthStencilAttachment">, value:LoadOp):Void;
	@:hlNative("xidl", "gpu_render_pass_depth_stencil_attachment_stencil_store_op")
	public static function stencilStoreOp(self:hl.Abstract<"xidl_GpuRenderPassDepthStencilAttachment">, value:StoreOp):Void;
	@:hlNative("xidl", "gpu_render_pass_depth_stencil_attachment_stencil_read_only")
	public static function stencilReadOnly(self:hl.Abstract<"xidl_GpuRenderPassDepthStencilAttachment">, value:Bool):Void;
}
