// Generated by xgpu-bindgen. Do not edit by hand.
package gpu;

abstract GpuShader(Int) from Int to Int {
	public inline function valid():Bool return GpuShaderNative.valid(this);
	public inline function destroy():Void GpuShaderNative.destroy(this);
	public inline function messages():String { var value = GpuShaderNative.messages(this); return value == null ? null : @:privateAccess String.fromUCS2(value); };
	public inline function getCompilationInfo():ash.Future<GpuCompilationInfo> return GpuShaderNative.getCompilationInfo(this);
}

private extern class GpuShaderNative {
	@:hlNative("xgpu", "gpu_shader_valid")
	public static function valid(self:Int):Bool;
	@:hlNative("xgpu", "gpu_shader_destroy")
	public static function destroy(self:Int):Void;
	@:hlNative("xgpu", "gpu_shader_messages")
	public static function messages(self:Int):hl.Bytes;
	@:hlNative("xgpu", "gpu_shader_get_compilation_info")
	public static function getCompilationInfo(self:Int):ash.Future<GpuCompilationInfo>;
}
