// Generated by xgpu-bindgen. Do not edit by hand.
package gpu;

abstract GpuSampler(Int) from Int to Int {
	public inline function valid():Bool return GpuSamplerNative.valid(this);
	public inline function destroy():Void GpuSamplerNative.destroy(this);
}

private extern class GpuSamplerNative {
	@:hlNative("xgpu", "gpu_sampler_valid")
	public static function valid(self:Int):Bool;
	@:hlNative("xgpu", "gpu_sampler_destroy")
	public static function destroy(self:Int):Void;
}
