// Generated by xgpu-bindgen. Do not edit by hand.
package gpu;

abstract GpuSamplerBindingLayout(hl.Abstract<"xgpu_GpuSamplerBindingLayout">) {
	public inline function new() this = GpuSamplerBindingLayoutNative.create();
	public inline function type(value:SamplerBindingType):Void GpuSamplerBindingLayoutNative.type(this, value);
}

private extern class GpuSamplerBindingLayoutNative {
	@:hlNative("xgpu", "gpu_sampler_binding_layout_new")
	public static function create():hl.Abstract<"xgpu_GpuSamplerBindingLayout">;
	@:hlNative("xgpu", "gpu_sampler_binding_layout_type")
	public static function type(self:hl.Abstract<"xgpu_GpuSamplerBindingLayout">, value:SamplerBindingType):Void;
}
