// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuSamplerDescriptor(hl.Abstract<"xidl_GpuSamplerDescriptor">) {
	public inline function new() this = GpuSamplerDescriptorNative.create();
	public inline function label(value:String):Void GpuSamplerDescriptorNative.label(this, value);
	public inline function addressModeU(value:AddressMode):Void GpuSamplerDescriptorNative.addressModeU(this, value);
	public inline function addressModeV(value:AddressMode):Void GpuSamplerDescriptorNative.addressModeV(this, value);
	public inline function addressModeW(value:AddressMode):Void GpuSamplerDescriptorNative.addressModeW(this, value);
	public inline function magFilter(value:FilterMode):Void GpuSamplerDescriptorNative.magFilter(this, value);
	public inline function minFilter(value:FilterMode):Void GpuSamplerDescriptorNative.minFilter(this, value);
	public inline function mipmapFilter(value:MipmapFilterMode):Void GpuSamplerDescriptorNative.mipmapFilter(this, value);
	public inline function lodMinClamp(value:Float):Void GpuSamplerDescriptorNative.lodMinClamp(this, value);
	public inline function lodMaxClamp(value:Float):Void GpuSamplerDescriptorNative.lodMaxClamp(this, value);
	public inline function compare(value:CompareFunction):Void GpuSamplerDescriptorNative.compare(this, value);
	public inline function maxAnisotropy(value:Int):Void GpuSamplerDescriptorNative.maxAnisotropy(this, value);
	public inline function borderColor(value:BorderColor):Void GpuSamplerDescriptorNative.borderColor(this, value);
}

private extern class GpuSamplerDescriptorNative {
	@:hlNative("xidl", "gpu_sampler_descriptor_new")
	public static function create():hl.Abstract<"xidl_GpuSamplerDescriptor">;
	@:hlNative("xidl", "gpu_sampler_descriptor_label")
	public static function label(self:hl.Abstract<"xidl_GpuSamplerDescriptor">, value:String):Void;
	@:hlNative("xidl", "gpu_sampler_descriptor_address_mode_u")
	public static function addressModeU(self:hl.Abstract<"xidl_GpuSamplerDescriptor">, value:AddressMode):Void;
	@:hlNative("xidl", "gpu_sampler_descriptor_address_mode_v")
	public static function addressModeV(self:hl.Abstract<"xidl_GpuSamplerDescriptor">, value:AddressMode):Void;
	@:hlNative("xidl", "gpu_sampler_descriptor_address_mode_w")
	public static function addressModeW(self:hl.Abstract<"xidl_GpuSamplerDescriptor">, value:AddressMode):Void;
	@:hlNative("xidl", "gpu_sampler_descriptor_mag_filter")
	public static function magFilter(self:hl.Abstract<"xidl_GpuSamplerDescriptor">, value:FilterMode):Void;
	@:hlNative("xidl", "gpu_sampler_descriptor_min_filter")
	public static function minFilter(self:hl.Abstract<"xidl_GpuSamplerDescriptor">, value:FilterMode):Void;
	@:hlNative("xidl", "gpu_sampler_descriptor_mipmap_filter")
	public static function mipmapFilter(self:hl.Abstract<"xidl_GpuSamplerDescriptor">, value:MipmapFilterMode):Void;
	@:hlNative("xidl", "gpu_sampler_descriptor_lod_min_clamp")
	public static function lodMinClamp(self:hl.Abstract<"xidl_GpuSamplerDescriptor">, value:Float):Void;
	@:hlNative("xidl", "gpu_sampler_descriptor_lod_max_clamp")
	public static function lodMaxClamp(self:hl.Abstract<"xidl_GpuSamplerDescriptor">, value:Float):Void;
	@:hlNative("xidl", "gpu_sampler_descriptor_compare")
	public static function compare(self:hl.Abstract<"xidl_GpuSamplerDescriptor">, value:CompareFunction):Void;
	@:hlNative("xidl", "gpu_sampler_descriptor_max_anisotropy")
	public static function maxAnisotropy(self:hl.Abstract<"xidl_GpuSamplerDescriptor">, value:Int):Void;
	@:hlNative("xidl", "gpu_sampler_descriptor_border_color")
	public static function borderColor(self:hl.Abstract<"xidl_GpuSamplerDescriptor">, value:BorderColor):Void;
}
