// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuStorageTextureBindingLayout(hl.Abstract<"xidl_GpuStorageTextureBindingLayout">) {
	public inline function new(format:TextureFormat) this = GpuStorageTextureBindingLayoutNative.create(format);
	public inline function access(value:StorageTextureAccess):Void GpuStorageTextureBindingLayoutNative.access(this, value);
	public inline function viewDimension(value:TextureViewDimension):Void GpuStorageTextureBindingLayoutNative.viewDimension(this, value);
}

private extern class GpuStorageTextureBindingLayoutNative {
	@:hlNative("xidl", "gpu_storage_texture_binding_layout_new")
	public static function create(format:TextureFormat):hl.Abstract<"xidl_GpuStorageTextureBindingLayout">;
	@:hlNative("xidl", "gpu_storage_texture_binding_layout_access")
	public static function access(self:hl.Abstract<"xidl_GpuStorageTextureBindingLayout">, value:StorageTextureAccess):Void;
	@:hlNative("xidl", "gpu_storage_texture_binding_layout_view_dimension")
	public static function viewDimension(self:hl.Abstract<"xidl_GpuStorageTextureBindingLayout">, value:TextureViewDimension):Void;
}
