// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuSamplerArray(hl.Abstract<"xgpu_GpuSamplerArray">) {
	public inline function new() this = GpuSamplerArrayNative.create();
	public inline function addSamplers(value:GpuSampler):Void GpuSamplerArrayNative.addSamplers(this, value);
}

private extern class GpuSamplerArrayNative {
	@:hlNative("xgpu", "gpu_sampler_array_new")
	public static function create():hl.Abstract<"xgpu_GpuSamplerArray">;
	@:hlNative("xgpu", "gpu_sampler_array_add_samplers")
	public static function addSamplers(self:hl.Abstract<"xgpu_GpuSamplerArray">, value:GpuSampler):Void;
}
