// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuSurface(Int) from Int to Int {
	public inline function valid():Bool return GpuSurfaceNative.valid(this);
	public inline function preferredFormat(adapter:GpuAdapter):TextureFormat return GpuSurfaceNative.preferredFormat(this, adapter);
	public inline function acquire():GpuTextureView return GpuSurfaceNative.acquire(this);
	public inline function destroy():Void GpuSurfaceNative.destroy(this);
	public inline function capabilities(adapter:GpuAdapter):GpuSurfaceCapabilities return GpuSurfaceNative.capabilities(this, adapter);
}

private extern class GpuSurfaceNative {
	@:hlNative("xgpu", "gpu_surface_valid")
	public static function valid(self:Int):Bool;
	@:hlNative("xgpu", "gpu_surface_preferred_format")
	public static function preferredFormat(self:Int, adapter:GpuAdapter):TextureFormat;
	@:hlNative("xgpu", "gpu_surface_acquire")
	public static function acquire(self:Int):GpuTextureView;
	@:hlNative("xgpu", "gpu_surface_destroy")
	public static function destroy(self:Int):Void;
	@:hlNative("xgpu", "gpu_surface_capabilities")
	public static function capabilities(self:Int, adapter:GpuAdapter):GpuSurfaceCapabilities;
}
