// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuSurfaceConfiguration(hl.Abstract<"xidl_GpuSurfaceConfiguration">) {
	public inline function new(format:TextureFormat, width:Int, height:Int) this = GpuSurfaceConfigurationNative.create(format, width, height);
	public inline function usage(value:Int):Void GpuSurfaceConfigurationNative.usage(this, value);
	public inline function addViewFormats(value:TextureFormat):Void GpuSurfaceConfigurationNative.addViewFormats(this, value);
	public inline function alphaMode(value:AlphaMode):Void GpuSurfaceConfigurationNative.alphaMode(this, value);
	public inline function presentMode(value:PresentMode):Void GpuSurfaceConfigurationNative.presentMode(this, value);
	public inline function colorSpace(value:ColorSpace):Void GpuSurfaceConfigurationNative.colorSpace(this, value);
	public inline function desiredMaximumFrameLatency(value:Int):Void GpuSurfaceConfigurationNative.desiredMaximumFrameLatency(this, value);
}

private extern class GpuSurfaceConfigurationNative {
	@:hlNative("xidl", "gpu_surface_configuration_new")
	public static function create(format:TextureFormat, width:Int, height:Int):hl.Abstract<"xidl_GpuSurfaceConfiguration">;
	@:hlNative("xidl", "gpu_surface_configuration_usage")
	public static function usage(self:hl.Abstract<"xidl_GpuSurfaceConfiguration">, value:Int):Void;
	@:hlNative("xidl", "gpu_surface_configuration_add_view_formats")
	public static function addViewFormats(self:hl.Abstract<"xidl_GpuSurfaceConfiguration">, value:TextureFormat):Void;
	@:hlNative("xidl", "gpu_surface_configuration_alpha_mode")
	public static function alphaMode(self:hl.Abstract<"xidl_GpuSurfaceConfiguration">, value:AlphaMode):Void;
	@:hlNative("xidl", "gpu_surface_configuration_present_mode")
	public static function presentMode(self:hl.Abstract<"xidl_GpuSurfaceConfiguration">, value:PresentMode):Void;
	@:hlNative("xidl", "gpu_surface_configuration_color_space")
	public static function colorSpace(self:hl.Abstract<"xidl_GpuSurfaceConfiguration">, value:ColorSpace):Void;
	@:hlNative("xidl", "gpu_surface_configuration_desired_maximum_frame_latency")
	public static function desiredMaximumFrameLatency(self:hl.Abstract<"xidl_GpuSurfaceConfiguration">, value:Int):Void;
}
