// Generated by xgpu-bindgen. Do not edit by hand.
package gpu;

abstract GpuStencilFaceState(hl.Abstract<"xgpu_GpuStencilFaceState">) {
	public inline function new() this = GpuStencilFaceStateNative.create();
	public inline function compare(value:CompareFunction):Void GpuStencilFaceStateNative.compare(this, value);
	public inline function failOp(value:StencilOperation):Void GpuStencilFaceStateNative.failOp(this, value);
	public inline function depthFailOp(value:StencilOperation):Void GpuStencilFaceStateNative.depthFailOp(this, value);
	public inline function passOp(value:StencilOperation):Void GpuStencilFaceStateNative.passOp(this, value);
}

private extern class GpuStencilFaceStateNative {
	@:hlNative("xgpu", "gpu_stencil_face_state_new")
	public static function create():hl.Abstract<"xgpu_GpuStencilFaceState">;
	@:hlNative("xgpu", "gpu_stencil_face_state_compare")
	public static function compare(self:hl.Abstract<"xgpu_GpuStencilFaceState">, value:CompareFunction):Void;
	@:hlNative("xgpu", "gpu_stencil_face_state_fail_op")
	public static function failOp(self:hl.Abstract<"xgpu_GpuStencilFaceState">, value:StencilOperation):Void;
	@:hlNative("xgpu", "gpu_stencil_face_state_depth_fail_op")
	public static function depthFailOp(self:hl.Abstract<"xgpu_GpuStencilFaceState">, value:StencilOperation):Void;
	@:hlNative("xgpu", "gpu_stencil_face_state_pass_op")
	public static function passOp(self:hl.Abstract<"xgpu_GpuStencilFaceState">, value:StencilOperation):Void;
}
