// Generated by xgpu-bindgen. Do not edit by hand.
package gpu;

abstract GpuSurfaceCapabilities(Int) from Int to Int {
	public inline function valid():Bool return GpuSurfaceCapabilitiesNative.valid(this);
	public inline function destroy():Void GpuSurfaceCapabilitiesNative.destroy(this);
	public inline function formatCount():Int return GpuSurfaceCapabilitiesNative.formatCount(this);
	public inline function format(index:Int):TextureFormat return GpuSurfaceCapabilitiesNative.format(this, index);
	public inline function presentModeCount():Int return GpuSurfaceCapabilitiesNative.presentModeCount(this);
	public inline function presentMode(index:Int):PresentMode return GpuSurfaceCapabilitiesNative.presentMode(this, index);
	public inline function alphaModeCount():Int return GpuSurfaceCapabilitiesNative.alphaModeCount(this);
	public inline function alphaMode(index:Int):AlphaMode return GpuSurfaceCapabilitiesNative.alphaMode(this, index);
	public inline function usages():Int return GpuSurfaceCapabilitiesNative.usages(this);
}

private extern class GpuSurfaceCapabilitiesNative {
	@:hlNative("xgpu", "gpu_surface_capabilities_valid")
	public static function valid(self:Int):Bool;
	@:hlNative("xgpu", "gpu_surface_capabilities_destroy")
	public static function destroy(self:Int):Void;
	@:hlNative("xgpu", "gpu_surface_capabilities_format_count")
	public static function formatCount(self:Int):Int;
	@:hlNative("xgpu", "gpu_surface_capabilities_format")
	public static function format(self:Int, index:Int):TextureFormat;
	@:hlNative("xgpu", "gpu_surface_capabilities_present_mode_count")
	public static function presentModeCount(self:Int):Int;
	@:hlNative("xgpu", "gpu_surface_capabilities_present_mode")
	public static function presentMode(self:Int, index:Int):PresentMode;
	@:hlNative("xgpu", "gpu_surface_capabilities_alpha_mode_count")
	public static function alphaModeCount(self:Int):Int;
	@:hlNative("xgpu", "gpu_surface_capabilities_alpha_mode")
	public static function alphaMode(self:Int, index:Int):AlphaMode;
	@:hlNative("xgpu", "gpu_surface_capabilities_usages")
	public static function usages(self:Int):Int;
}
