// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuShaderModuleDescriptor(hl.Abstract<"xidl_GpuShaderModuleDescriptor">) {
	public inline function new(code:String) this = GpuShaderModuleDescriptorNative.create(code);
	public inline function label(value:String):Void GpuShaderModuleDescriptorNative.label(this, value);
	public inline function boundsChecks(value:Bool):Void GpuShaderModuleDescriptorNative.boundsChecks(this, value);
	public inline function forceLoopBounding(value:Bool):Void GpuShaderModuleDescriptorNative.forceLoopBounding(this, value);
	public inline function rayQueryInitializationTracking(value:Bool):Void GpuShaderModuleDescriptorNative.rayQueryInitializationTracking(this, value);
	public inline function taskShaderDispatchTracking(value:Bool):Void GpuShaderModuleDescriptorNative.taskShaderDispatchTracking(this, value);
	public inline function meshShaderPrimitiveIndicesClamp(value:Bool):Void GpuShaderModuleDescriptorNative.meshShaderPrimitiveIndicesClamp(this, value);
	public inline function intDivChecks(value:Bool):Void GpuShaderModuleDescriptorNative.intDivChecks(this, value);
}

private extern class GpuShaderModuleDescriptorNative {
	@:hlNative("xidl", "gpu_shader_module_descriptor_new")
	public static function create(code:String):hl.Abstract<"xidl_GpuShaderModuleDescriptor">;
	@:hlNative("xidl", "gpu_shader_module_descriptor_label")
	public static function label(self:hl.Abstract<"xidl_GpuShaderModuleDescriptor">, value:String):Void;
	@:hlNative("xidl", "gpu_shader_module_descriptor_bounds_checks")
	public static function boundsChecks(self:hl.Abstract<"xidl_GpuShaderModuleDescriptor">, value:Bool):Void;
	@:hlNative("xidl", "gpu_shader_module_descriptor_force_loop_bounding")
	public static function forceLoopBounding(self:hl.Abstract<"xidl_GpuShaderModuleDescriptor">, value:Bool):Void;
	@:hlNative("xidl", "gpu_shader_module_descriptor_ray_query_initialization_tracking")
	public static function rayQueryInitializationTracking(self:hl.Abstract<"xidl_GpuShaderModuleDescriptor">, value:Bool):Void;
	@:hlNative("xidl", "gpu_shader_module_descriptor_task_shader_dispatch_tracking")
	public static function taskShaderDispatchTracking(self:hl.Abstract<"xidl_GpuShaderModuleDescriptor">, value:Bool):Void;
	@:hlNative("xidl", "gpu_shader_module_descriptor_mesh_shader_primitive_indices_clamp")
	public static function meshShaderPrimitiveIndicesClamp(self:hl.Abstract<"xidl_GpuShaderModuleDescriptor">, value:Bool):Void;
	@:hlNative("xidl", "gpu_shader_module_descriptor_int_div_checks")
	public static function intDivChecks(self:hl.Abstract<"xidl_GpuShaderModuleDescriptor">, value:Bool):Void;
}
