// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuTexelCopyBufferInfo(hl.Abstract<"xgpu_GpuTexelCopyBufferInfo">) {
	public inline function new(buffer:GpuBuffer) this = GpuTexelCopyBufferInfoNative.create(buffer);
	public inline function offset(value:haxe.Int64):Void GpuTexelCopyBufferInfoNative.offset(this, value);
	public inline function bytesPerRow(value:Int):Void GpuTexelCopyBufferInfoNative.bytesPerRow(this, value);
	public inline function rowsPerImage(value:Int):Void GpuTexelCopyBufferInfoNative.rowsPerImage(this, value);
}

private extern class GpuTexelCopyBufferInfoNative {
	@:hlNative("xgpu", "gpu_texel_copy_buffer_info_new")
	public static function create(buffer:GpuBuffer):hl.Abstract<"xgpu_GpuTexelCopyBufferInfo">;
	@:hlNative("xgpu", "gpu_texel_copy_buffer_info_offset")
	public static function offset(self:hl.Abstract<"xgpu_GpuTexelCopyBufferInfo">, value:haxe.Int64):Void;
	@:hlNative("xgpu", "gpu_texel_copy_buffer_info_bytes_per_row")
	public static function bytesPerRow(self:hl.Abstract<"xgpu_GpuTexelCopyBufferInfo">, value:Int):Void;
	@:hlNative("xgpu", "gpu_texel_copy_buffer_info_rows_per_image")
	public static function rowsPerImage(self:hl.Abstract<"xgpu_GpuTexelCopyBufferInfo">, value:Int):Void;
}
