// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuTlasDescriptor(hl.Abstract<"xgpu_GpuTlasDescriptor">) {
	public inline function new(maxInstances:Int) this = GpuTlasDescriptorNative.create(maxInstances);
	public inline function label(value:String):Void GpuTlasDescriptorNative.label(this, value);
	public inline function flags(value:Int):Void GpuTlasDescriptorNative.flags(this, value);
	public inline function updateMode(value:AccelerationStructureUpdateMode):Void GpuTlasDescriptorNative.updateMode(this, value);
}

private extern class GpuTlasDescriptorNative {
	@:hlNative("xgpu", "gpu_tlas_descriptor_new")
	public static function create(maxInstances:Int):hl.Abstract<"xgpu_GpuTlasDescriptor">;
	@:hlNative("xgpu", "gpu_tlas_descriptor_label")
	public static function label(self:hl.Abstract<"xgpu_GpuTlasDescriptor">, value:String):Void;
	@:hlNative("xgpu", "gpu_tlas_descriptor_flags")
	public static function flags(self:hl.Abstract<"xgpu_GpuTlasDescriptor">, value:Int):Void;
	@:hlNative("xgpu", "gpu_tlas_descriptor_update_mode")
	public static function updateMode(self:hl.Abstract<"xgpu_GpuTlasDescriptor">, value:AccelerationStructureUpdateMode):Void;
}
