// Generated by xgpu-bindgen. Do not edit by hand.
package gpu;

abstract GpuTextureViewDescriptor(hl.Abstract<"xgpu_GpuTextureViewDescriptor">) {
	public inline function new() this = GpuTextureViewDescriptorNative.create();
	public inline function label(value:String):Void GpuTextureViewDescriptorNative.label(this, value);
	public inline function format(value:TextureFormat):Void GpuTextureViewDescriptorNative.format(this, value);
	public inline function dimension(value:TextureViewDimension):Void GpuTextureViewDescriptorNative.dimension(this, value);
	public inline function usage(value:Int):Void GpuTextureViewDescriptorNative.usage(this, value);
	public inline function aspect(value:TextureAspect):Void GpuTextureViewDescriptorNative.aspect(this, value);
	public inline function baseMipLevel(value:Int):Void GpuTextureViewDescriptorNative.baseMipLevel(this, value);
	public inline function mipLevelCount(value:Int):Void GpuTextureViewDescriptorNative.mipLevelCount(this, value);
	public inline function baseArrayLayer(value:Int):Void GpuTextureViewDescriptorNative.baseArrayLayer(this, value);
	public inline function arrayLayerCount(value:Int):Void GpuTextureViewDescriptorNative.arrayLayerCount(this, value);
	public inline function swizzle(value:String):Void GpuTextureViewDescriptorNative.swizzle(this, value);
}

private extern class GpuTextureViewDescriptorNative {
	@:hlNative("xgpu", "gpu_texture_view_descriptor_new")
	public static function create():hl.Abstract<"xgpu_GpuTextureViewDescriptor">;
	@:hlNative("xgpu", "gpu_texture_view_descriptor_label")
	public static function label(self:hl.Abstract<"xgpu_GpuTextureViewDescriptor">, value:String):Void;
	@:hlNative("xgpu", "gpu_texture_view_descriptor_format")
	public static function format(self:hl.Abstract<"xgpu_GpuTextureViewDescriptor">, value:TextureFormat):Void;
	@:hlNative("xgpu", "gpu_texture_view_descriptor_dimension")
	public static function dimension(self:hl.Abstract<"xgpu_GpuTextureViewDescriptor">, value:TextureViewDimension):Void;
	@:hlNative("xgpu", "gpu_texture_view_descriptor_usage")
	public static function usage(self:hl.Abstract<"xgpu_GpuTextureViewDescriptor">, value:Int):Void;
	@:hlNative("xgpu", "gpu_texture_view_descriptor_aspect")
	public static function aspect(self:hl.Abstract<"xgpu_GpuTextureViewDescriptor">, value:TextureAspect):Void;
	@:hlNative("xgpu", "gpu_texture_view_descriptor_base_mip_level")
	public static function baseMipLevel(self:hl.Abstract<"xgpu_GpuTextureViewDescriptor">, value:Int):Void;
	@:hlNative("xgpu", "gpu_texture_view_descriptor_mip_level_count")
	public static function mipLevelCount(self:hl.Abstract<"xgpu_GpuTextureViewDescriptor">, value:Int):Void;
	@:hlNative("xgpu", "gpu_texture_view_descriptor_base_array_layer")
	public static function baseArrayLayer(self:hl.Abstract<"xgpu_GpuTextureViewDescriptor">, value:Int):Void;
	@:hlNative("xgpu", "gpu_texture_view_descriptor_array_layer_count")
	public static function arrayLayerCount(self:hl.Abstract<"xgpu_GpuTextureViewDescriptor">, value:Int):Void;
	@:hlNative("xgpu", "gpu_texture_view_descriptor_swizzle")
	public static function swizzle(self:hl.Abstract<"xgpu_GpuTextureViewDescriptor">, value:String):Void;
}
