// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuTextureBindingLayout(hl.Abstract<"xgpu_GpuTextureBindingLayout">) {
	public inline function new() this = GpuTextureBindingLayoutNative.create();
	public inline function sampleType(value:TextureSampleType):Void GpuTextureBindingLayoutNative.sampleType(this, value);
	public inline function viewDimension(value:TextureViewDimension):Void GpuTextureBindingLayoutNative.viewDimension(this, value);
	public inline function multisampled(value:Bool):Void GpuTextureBindingLayoutNative.multisampled(this, value);
}

private extern class GpuTextureBindingLayoutNative {
	@:hlNative("xgpu", "gpu_texture_binding_layout_new")
	public static function create():hl.Abstract<"xgpu_GpuTextureBindingLayout">;
	@:hlNative("xgpu", "gpu_texture_binding_layout_sample_type")
	public static function sampleType(self:hl.Abstract<"xgpu_GpuTextureBindingLayout">, value:TextureSampleType):Void;
	@:hlNative("xgpu", "gpu_texture_binding_layout_view_dimension")
	public static function viewDimension(self:hl.Abstract<"xgpu_GpuTextureBindingLayout">, value:TextureViewDimension):Void;
	@:hlNative("xgpu", "gpu_texture_binding_layout_multisampled")
	public static function multisampled(self:hl.Abstract<"xgpu_GpuTextureBindingLayout">, value:Bool):Void;
}
