// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuTexelCopyTextureInfo(hl.Abstract<"xgpu_GpuTexelCopyTextureInfo">) {
	public inline function new(texture:GpuTexture) this = GpuTexelCopyTextureInfoNative.create(texture);
	public inline function mipLevel(value:Int):Void GpuTexelCopyTextureInfoNative.mipLevel(this, value);
	public inline function origin(value:GpuOrigin3D):Void GpuTexelCopyTextureInfoNative.origin(this, value);
	public inline function aspect(value:TextureAspect):Void GpuTexelCopyTextureInfoNative.aspect(this, value);
}

private extern class GpuTexelCopyTextureInfoNative {
	@:hlNative("xgpu", "gpu_texel_copy_texture_info_new")
	public static function create(texture:GpuTexture):hl.Abstract<"xgpu_GpuTexelCopyTextureInfo">;
	@:hlNative("xgpu", "gpu_texel_copy_texture_info_mip_level")
	public static function mipLevel(self:hl.Abstract<"xgpu_GpuTexelCopyTextureInfo">, value:Int):Void;
	@:hlNative("xgpu", "gpu_texel_copy_texture_info_origin")
	public static function origin(self:hl.Abstract<"xgpu_GpuTexelCopyTextureInfo">, value:GpuOrigin3D):Void;
	@:hlNative("xgpu", "gpu_texel_copy_texture_info_aspect")
	public static function aspect(self:hl.Abstract<"xgpu_GpuTexelCopyTextureInfo">, value:TextureAspect):Void;
}
