// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuTlasInstance(hl.Abstract<"xgpu_GpuTlasInstance">) {
	public inline function new(blas:GpuBlas) this = GpuTlasInstanceNative.create(blas);
	public inline function addTransform(value:Float):Void GpuTlasInstanceNative.addTransform(this, value);
	public inline function customData(value:Int):Void GpuTlasInstanceNative.customData(this, value);
	public inline function mask(value:Int):Void GpuTlasInstanceNative.mask(this, value);
}

private extern class GpuTlasInstanceNative {
	@:hlNative("xgpu", "gpu_tlas_instance_new")
	public static function create(blas:GpuBlas):hl.Abstract<"xgpu_GpuTlasInstance">;
	@:hlNative("xgpu", "gpu_tlas_instance_add_transform")
	public static function addTransform(self:hl.Abstract<"xgpu_GpuTlasInstance">, value:Float):Void;
	@:hlNative("xgpu", "gpu_tlas_instance_custom_data")
	public static function customData(self:hl.Abstract<"xgpu_GpuTlasInstance">, value:Int):Void;
	@:hlNative("xgpu", "gpu_tlas_instance_mask")
	public static function mask(self:hl.Abstract<"xgpu_GpuTlasInstance">, value:Int):Void;
}
