// Generated by xgpu-bindgen. Do not edit by hand.
package gpu;

abstract GpuTlasArray(hl.Abstract<"xgpu_GpuTlasArray">) {
	public inline function new() this = GpuTlasArrayNative.create();
	public inline function addTlases(value:GpuTlas):Void GpuTlasArrayNative.addTlases(this, value);
}

private extern class GpuTlasArrayNative {
	@:hlNative("xgpu", "gpu_tlas_array_new")
	public static function create():hl.Abstract<"xgpu_GpuTlasArray">;
	@:hlNative("xgpu", "gpu_tlas_array_add_tlases")
	public static function addTlases(self:hl.Abstract<"xgpu_GpuTlasArray">, value:GpuTlas):Void;
}
