// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuTextureViewArray(hl.Abstract<"xidl_GpuTextureViewArray">) {
	public inline function new() this = GpuTextureViewArrayNative.create();
	public inline function addViews(value:GpuTextureView):Void GpuTextureViewArrayNative.addViews(this, value);
}

private extern class GpuTextureViewArrayNative {
	@:hlNative("xidl", "gpu_texture_view_array_new")
	public static function create():hl.Abstract<"xidl_GpuTextureViewArray">;
	@:hlNative("xidl", "gpu_texture_view_array_add_views")
	public static function addViews(self:hl.Abstract<"xidl_GpuTextureViewArray">, value:GpuTextureView):Void;
}
