// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuTextureViewArray(hl.Abstract<"xgpu_GpuTextureViewArray">) {
	public inline function new() this = GpuTextureViewArrayNative.create();
	public inline function addViews(value:GpuTextureView):Void GpuTextureViewArrayNative.addViews(this, value);
}

private extern class GpuTextureViewArrayNative {
	@:hlNative("xgpu", "gpu_texture_view_array_new")
	public static function create():hl.Abstract<"xgpu_GpuTextureViewArray">;
	@:hlNative("xgpu", "gpu_texture_view_array_add_views")
	public static function addViews(self:hl.Abstract<"xgpu_GpuTextureViewArray">, value:GpuTextureView):Void;
}
