// Generated by xgpu-bindgen. Do not edit by hand.
package gpu;

abstract GpuTextureView(Int) from Int to Int {
	public inline function valid():Bool return GpuTextureViewNative.valid(this);
	public inline function destroy():Void GpuTextureViewNative.destroy(this);
}

private extern class GpuTextureViewNative {
	@:hlNative("xgpu", "gpu_texture_view_valid")
	public static function valid(self:Int):Bool;
	@:hlNative("xgpu", "gpu_texture_view_destroy")
	public static function destroy(self:Int):Void;
}
