// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuTexelCopyBufferLayout(hl.Abstract<"xidl_GpuTexelCopyBufferLayout">) {
	public inline function new() this = GpuTexelCopyBufferLayoutNative.create();
	public inline function offset(value:haxe.Int64):Void GpuTexelCopyBufferLayoutNative.offset(this, value);
	public inline function bytesPerRow(value:Int):Void GpuTexelCopyBufferLayoutNative.bytesPerRow(this, value);
	public inline function rowsPerImage(value:Int):Void GpuTexelCopyBufferLayoutNative.rowsPerImage(this, value);
}

private extern class GpuTexelCopyBufferLayoutNative {
	@:hlNative("xidl", "gpu_texel_copy_buffer_layout_new")
	public static function create():hl.Abstract<"xidl_GpuTexelCopyBufferLayout">;
	@:hlNative("xidl", "gpu_texel_copy_buffer_layout_offset")
	public static function offset(self:hl.Abstract<"xidl_GpuTexelCopyBufferLayout">, value:haxe.Int64):Void;
	@:hlNative("xidl", "gpu_texel_copy_buffer_layout_bytes_per_row")
	public static function bytesPerRow(self:hl.Abstract<"xidl_GpuTexelCopyBufferLayout">, value:Int):Void;
	@:hlNative("xidl", "gpu_texel_copy_buffer_layout_rows_per_image")
	public static function rowsPerImage(self:hl.Abstract<"xidl_GpuTexelCopyBufferLayout">, value:Int):Void;
}
