// Generated by xgpu-bindgen. Do not edit by hand.
package gpu;

abstract GpuTextureDescriptor(hl.Abstract<"xgpu_GpuTextureDescriptor">) {
	public inline function new(size:GpuExtent3D, format:TextureFormat, usage:Int) this = GpuTextureDescriptorNative.create(size, format, usage);
	public inline function label(value:String):Void GpuTextureDescriptorNative.label(this, value);
	public inline function mipLevelCount(value:Int):Void GpuTextureDescriptorNative.mipLevelCount(this, value);
	public inline function sampleCount(value:Int):Void GpuTextureDescriptorNative.sampleCount(this, value);
	public inline function dimension(value:TextureDimension):Void GpuTextureDescriptorNative.dimension(this, value);
	public inline function addViewFormats(value:TextureFormat):Void GpuTextureDescriptorNative.addViewFormats(this, value);
	public inline function textureBindingViewDimension(value:TextureViewDimension):Void GpuTextureDescriptorNative.textureBindingViewDimension(this, value);
}

private extern class GpuTextureDescriptorNative {
	@:hlNative("xgpu", "gpu_texture_descriptor_new")
	public static function create(size:GpuExtent3D, format:TextureFormat, usage:Int):hl.Abstract<"xgpu_GpuTextureDescriptor">;
	@:hlNative("xgpu", "gpu_texture_descriptor_label")
	public static function label(self:hl.Abstract<"xgpu_GpuTextureDescriptor">, value:String):Void;
	@:hlNative("xgpu", "gpu_texture_descriptor_mip_level_count")
	public static function mipLevelCount(self:hl.Abstract<"xgpu_GpuTextureDescriptor">, value:Int):Void;
	@:hlNative("xgpu", "gpu_texture_descriptor_sample_count")
	public static function sampleCount(self:hl.Abstract<"xgpu_GpuTextureDescriptor">, value:Int):Void;
	@:hlNative("xgpu", "gpu_texture_descriptor_dimension")
	public static function dimension(self:hl.Abstract<"xgpu_GpuTextureDescriptor">, value:TextureDimension):Void;
	@:hlNative("xgpu", "gpu_texture_descriptor_add_view_formats")
	public static function addViewFormats(self:hl.Abstract<"xgpu_GpuTextureDescriptor">, value:TextureFormat):Void;
	@:hlNative("xgpu", "gpu_texture_descriptor_texture_binding_view_dimension")
	public static function textureBindingViewDimension(self:hl.Abstract<"xgpu_GpuTextureDescriptor">, value:TextureViewDimension):Void;
}
