// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuTexture(Int) from Int to Int {
	public inline function valid():Bool return GpuTextureNative.valid(this);
	public inline function createView(descriptor:GpuTextureViewDescriptor):GpuTextureView return GpuTextureNative.createView(this, descriptor);
	public inline function destroy():Void GpuTextureNative.destroy(this);
	public inline function width():Int return GpuTextureNative.width(this);
	public inline function height():Int return GpuTextureNative.height(this);
	public inline function depthOrArrayLayers():Int return GpuTextureNative.depthOrArrayLayers(this);
	public inline function mipLevelCount():Int return GpuTextureNative.mipLevelCount(this);
	public inline function sampleCount():Int return GpuTextureNative.sampleCount(this);
	public inline function dimension():TextureDimension return GpuTextureNative.dimension(this);
	public inline function format():TextureFormat return GpuTextureNative.format(this);
	public inline function usage():Int return GpuTextureNative.usage(this);
}

private extern class GpuTextureNative {
	@:hlNative("xgpu", "gpu_texture_valid")
	public static function valid(self:Int):Bool;
	@:hlNative("xgpu", "gpu_texture_create_view")
	public static function createView(self:Int, descriptor:GpuTextureViewDescriptor):GpuTextureView;
	@:hlNative("xgpu", "gpu_texture_destroy")
	public static function destroy(self:Int):Void;
	@:hlNative("xgpu", "gpu_texture_width")
	public static function width(self:Int):Int;
	@:hlNative("xgpu", "gpu_texture_height")
	public static function height(self:Int):Int;
	@:hlNative("xgpu", "gpu_texture_depth_or_array_layers")
	public static function depthOrArrayLayers(self:Int):Int;
	@:hlNative("xgpu", "gpu_texture_mip_level_count")
	public static function mipLevelCount(self:Int):Int;
	@:hlNative("xgpu", "gpu_texture_sample_count")
	public static function sampleCount(self:Int):Int;
	@:hlNative("xgpu", "gpu_texture_dimension")
	public static function dimension(self:Int):TextureDimension;
	@:hlNative("xgpu", "gpu_texture_format")
	public static function format(self:Int):TextureFormat;
	@:hlNative("xgpu", "gpu_texture_usage")
	public static function usage(self:Int):Int;
}
