// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuTlas(Int) from Int to Int {
	public inline function valid():Bool return GpuTlasNative.valid(this);
	public inline function destroy():Void GpuTlasNative.destroy(this);
	public inline function maxInstances():Int return GpuTlasNative.maxInstances(this);
	public inline function setInstance(index:Int, instance:GpuTlasInstance):Void GpuTlasNative.setInstance(this, index, instance);
	public inline function clearInstance(index:Int):Void GpuTlasNative.clearInstance(this, index);
}

private extern class GpuTlasNative {
	@:hlNative("xidl", "gpu_tlas_valid")
	public static function valid(self:Int):Bool;
	@:hlNative("xidl", "gpu_tlas_destroy")
	public static function destroy(self:Int):Void;
	@:hlNative("xidl", "gpu_tlas_max_instances")
	public static function maxInstances(self:Int):Int;
	@:hlNative("xidl", "gpu_tlas_set_instance")
	public static function setInstance(self:Int, index:Int, instance:GpuTlasInstance):Void;
	@:hlNative("xidl", "gpu_tlas_clear_instance")
	public static function clearInstance(self:Int, index:Int):Void;
}
