// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuVertexState(hl.Abstract<"xgpu_GpuVertexState">) {
	public inline function new(module:GpuShader) this = GpuVertexStateNative.create(module);
	public inline function entryPoint(value:String):Void GpuVertexStateNative.entryPoint(this, value);
	public inline function addConstants(key:String, value:Float):Void GpuVertexStateNative.addConstants(this, key, value);
	public inline function addBuffers(value:GpuVertexBufferLayout):Void GpuVertexStateNative.addBuffers(this, value);
}

private extern class GpuVertexStateNative {
	@:hlNative("xgpu", "gpu_vertex_state_new")
	public static function create(module:GpuShader):hl.Abstract<"xgpu_GpuVertexState">;
	@:hlNative("xgpu", "gpu_vertex_state_entry_point")
	public static function entryPoint(self:hl.Abstract<"xgpu_GpuVertexState">, value:String):Void;
	@:hlNative("xgpu", "gpu_vertex_state_add_constants")
	public static function addConstants(self:hl.Abstract<"xgpu_GpuVertexState">, key:String, value:Float):Void;
	@:hlNative("xgpu", "gpu_vertex_state_add_buffers")
	public static function addBuffers(self:hl.Abstract<"xgpu_GpuVertexState">, value:GpuVertexBufferLayout):Void;
}
