// Generated by xgpu-bindgen. Do not edit by hand.
package gpu;

abstract GpuVertexAttribute(hl.Abstract<"xgpu_GpuVertexAttribute">) {
	public inline function new(format:VertexFormat, offset:haxe.Int64, shaderLocation:Int) this = GpuVertexAttributeNative.create(format, offset, shaderLocation);
}

private extern class GpuVertexAttributeNative {
	@:hlNative("xgpu", "gpu_vertex_attribute_new")
	public static function create(format:VertexFormat, offset:haxe.Int64, shaderLocation:Int):hl.Abstract<"xgpu_GpuVertexAttribute">;
}
