// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

abstract GpuVertexBufferLayout(hl.Abstract<"xidl_GpuVertexBufferLayout">) {
	public inline function new(arrayStride:haxe.Int64) this = GpuVertexBufferLayoutNative.create(arrayStride);
	public inline function stepMode(value:VertexStepMode):Void GpuVertexBufferLayoutNative.stepMode(this, value);
	public inline function addAttributes(value:GpuVertexAttribute):Void GpuVertexBufferLayoutNative.addAttributes(this, value);
}

private extern class GpuVertexBufferLayoutNative {
	@:hlNative("xidl", "gpu_vertex_buffer_layout_new")
	public static function create(arrayStride:haxe.Int64):hl.Abstract<"xidl_GpuVertexBufferLayout">;
	@:hlNative("xidl", "gpu_vertex_buffer_layout_step_mode")
	public static function stepMode(self:hl.Abstract<"xidl_GpuVertexBufferLayout">, value:VertexStepMode):Void;
	@:hlNative("xidl", "gpu_vertex_buffer_layout_add_attributes")
	public static function addAttributes(self:hl.Abstract<"xidl_GpuVertexBufferLayout">, value:GpuVertexAttribute):Void;
}
