// Generated by xidl-bindgen. Do not edit by hand.
package gpu;

@:noCompletion
class XidlBytes {
	public static function take(value:hl.Abstract<"xgpu_buffer_result">):haxe.io.Bytes {
		if (value == null) return null;
		var out = haxe.io.Bytes.alloc(XidlBytesNative.length(value));
		XidlBytesNative.copy(value, out);
		return out;
	}
}

private extern class XidlBytesNative {
	@:hlNative("xgpu", "buffer_result_len")
	public static function length(value:hl.Abstract<"xgpu_buffer_result">):Int;
	@:hlNative("xgpu", "buffer_result_copy")
	public static function copy(value:hl.Abstract<"xgpu_buffer_result">, out:haxe.io.Bytes):Void;
}
